# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from py4heappe.heappe_v6.core.api_client import ApiClient


class CredentialsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def heappe_credentials_create_credential_post(self, **kwargs):  # noqa: E501
        """Creates a new credential. Fill only the properties relevant to the selected AuthType.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_credentials_create_credential_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CreateCredentialModel body:
        :return: CredentialResponseExt
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_credentials_create_credential_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_credentials_create_credential_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_credentials_create_credential_post_with_http_info(self, **kwargs):  # noqa: E501
        """Creates a new credential. Fill only the properties relevant to the selected AuthType.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_credentials_create_credential_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param CreateCredentialModel body:
        :return: CredentialResponseExt
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_credentials_create_credential_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Credentials/CreateCredential', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='CredentialResponseExt',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_credentials_get_credentials_get(self, **kwargs):  # noqa: E501
        """Gets a list of credentials for a project.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_credentials_get_credentials_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int ProjectId:
        :param str SessionCode:
        :param int AdaptorUserId:
        :return: list[CredentialResponseExt]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_credentials_get_credentials_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_credentials_get_credentials_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_credentials_get_credentials_get_with_http_info(self, **kwargs):  # noqa: E501
        """Gets a list of credentials for a project.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_credentials_get_credentials_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int ProjectId:
        :param str SessionCode:
        :param int AdaptorUserId:
        :return: list[CredentialResponseExt]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ProjectId', 'SessionCode', 'AdaptorUserId']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_credentials_get_credentials_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'ProjectId' in params:
            query_params.append(('ProjectId', params['ProjectId']))  # noqa: E501
        if 'SessionCode' in params:
            query_params.append(('SessionCode', params['SessionCode']))  # noqa: E501
        if 'AdaptorUserId' in params:
            query_params.append(('AdaptorUserId', params['AdaptorUserId']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Credentials/GetCredentials', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[CredentialResponseExt]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_credentials_modify_credential_put(self, **kwargs):  # noqa: E501
        """Modifies credential for a project.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_credentials_modify_credential_put(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ModifyCredentialModel body:
        :return: list[CredentialResponseExt]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_credentials_modify_credential_put_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_credentials_modify_credential_put_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_credentials_modify_credential_put_with_http_info(self, **kwargs):  # noqa: E501
        """Modifies credential for a project.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_credentials_modify_credential_put_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ModifyCredentialModel body:
        :return: list[CredentialResponseExt]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_credentials_modify_credential_put" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Credentials/ModifyCredential', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[CredentialResponseExt]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_credentials_remove_credential_delete(self, **kwargs):  # noqa: E501
        """Remove credential for a project.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_credentials_remove_credential_delete(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param RemoveCredentialModel body:
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_credentials_remove_credential_delete_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_credentials_remove_credential_delete_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_credentials_remove_credential_delete_with_http_info(self, **kwargs):  # noqa: E501
        """Remove credential for a project.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_credentials_remove_credential_delete_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param RemoveCredentialModel body:
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_credentials_remove_credential_delete" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/json', 'application/*+json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Credentials/RemoveCredential', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
