# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from py4heappe.heappe_v6.core.api_client import ApiClient


class DictionaryApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def heappe_dictionary_get_accounting_state_types_get(self, **kwargs):  # noqa: E501
        """Get accounting state types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_accounting_state_types_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_accounting_state_types_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_accounting_state_types_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_accounting_state_types_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get accounting state types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_accounting_state_types_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_accounting_state_types_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetAccountingStateTypes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_adaptor_user_types_get(self, **kwargs):  # noqa: E501
        """Get adaptor user types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_adaptor_user_types_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_adaptor_user_types_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_adaptor_user_types_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_adaptor_user_types_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get adaptor user types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_adaptor_user_types_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_adaptor_user_types_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetAdaptorUserTypes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_cluster_authentication_credentials_auth_types_get(self, **kwargs):  # noqa: E501
        """Get cluster authentication credentials auth types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_cluster_authentication_credentials_auth_types_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_cluster_authentication_credentials_auth_types_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_cluster_authentication_credentials_auth_types_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_cluster_authentication_credentials_auth_types_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get cluster authentication credentials auth types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_cluster_authentication_credentials_auth_types_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_cluster_authentication_credentials_auth_types_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetClusterAuthenticationCredentialsAuthTypes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_cluster_connection_protocols_get(self, **kwargs):  # noqa: E501
        """Get cluster connection protocols mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_cluster_connection_protocols_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_cluster_connection_protocols_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_cluster_connection_protocols_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_cluster_connection_protocols_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get cluster connection protocols mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_cluster_connection_protocols_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_cluster_connection_protocols_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetClusterConnectionProtocols', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_database_backup_types_get(self, **kwargs):  # noqa: E501
        """Get database backup types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_database_backup_types_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_database_backup_types_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_database_backup_types_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_database_backup_types_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get database backup types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_database_backup_types_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_database_backup_types_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetDatabaseBackupTypes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_deployment_types_get(self, **kwargs):  # noqa: E501
        """Get deployment types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_deployment_types_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_deployment_types_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_deployment_types_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_deployment_types_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get deployment types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_deployment_types_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_deployment_types_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetDeploymentTypes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_file_transfer_cipher_types_get(self, **kwargs):  # noqa: E501
        """Get file transfer cipher types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_file_transfer_cipher_types_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_file_transfer_cipher_types_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_file_transfer_cipher_types_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_file_transfer_cipher_types_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get file transfer cipher types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_file_transfer_cipher_types_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_file_transfer_cipher_types_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetFileTransferCipherTypes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_file_transfer_protocols_get(self, **kwargs):  # noqa: E501
        """Get file transfer protocols mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_file_transfer_protocols_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_file_transfer_protocols_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_file_transfer_protocols_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_file_transfer_protocols_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get file transfer protocols mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_file_transfer_protocols_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_file_transfer_protocols_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetFileTransferProtocols', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_job_states_get(self, **kwargs):  # noqa: E501
        """Get job states mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_job_states_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_job_states_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_job_states_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_job_states_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get job states mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_job_states_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_job_states_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetJobStates', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_proxy_types_get(self, **kwargs):  # noqa: E501
        """Get proxy types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_proxy_types_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_proxy_types_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_proxy_types_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_proxy_types_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get proxy types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_proxy_types_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_proxy_types_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetProxyTypes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_resource_allocation_types_get(self, **kwargs):  # noqa: E501
        """Get resource allocation types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_resource_allocation_types_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_resource_allocation_types_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_resource_allocation_types_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_resource_allocation_types_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get resource allocation types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_resource_allocation_types_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_resource_allocation_types_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetResourceAllocationTypes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_scheduler_types_get(self, **kwargs):  # noqa: E501
        """Get scheduler types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_scheduler_types_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_scheduler_types_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_scheduler_types_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_scheduler_types_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get scheduler types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_scheduler_types_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_scheduler_types_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetSchedulerTypes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_synchronizable_files_get(self, **kwargs):  # noqa: E501
        """Get synchronizable files mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_synchronizable_files_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_synchronizable_files_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_synchronizable_files_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_synchronizable_files_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get synchronizable files mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_synchronizable_files_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_synchronizable_files_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetSynchronizableFiles', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_task_priorities_get(self, **kwargs):  # noqa: E501
        """Get task priorities mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_task_priorities_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_task_priorities_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_task_priorities_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_task_priorities_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get task priorities mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_task_priorities_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_task_priorities_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetTaskPriorities', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_task_states_get(self, **kwargs):  # noqa: E501
        """Get task states mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_task_states_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_task_states_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_task_states_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_task_states_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get task states mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_task_states_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_task_states_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetTaskStates', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heappe_dictionary_get_usage_types_get(self, **kwargs):  # noqa: E501
        """Get usage types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_usage_types_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heappe_dictionary_get_usage_types_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heappe_dictionary_get_usage_types_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heappe_dictionary_get_usage_types_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get usage types mapping (External)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heappe_dictionary_get_usage_types_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[DictionaryItemModel]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heappe_dictionary_get_usage_types_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Bearer', 'ServiceApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/heappe/Dictionary/GetUsageTypes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[DictionaryItemModel]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
