## GENERATION STAGE

API_client_generation:
  stage: API_generation
  image: eclipse-temurin:11-jdk
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH != "main"'
  before_script:
    - |
      if [ -x "$(command -v dnf)" ]; then
        dnf -y install wget zip
      elif [ -x "$(command -v yum)" ]; then
        yum -y install wget zip
      else
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -qq
        apt-get install -y --no-install-recommends wget zip
        rm -rf /var/lib/apt/lists/*
      fi
    - wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.71/swagger-codegen-cli-3.0.71.jar -O /swagger-codegen-cli.jar
  script:
    - echo "Generation API client"
    - java -jar /swagger-codegen-cli.jar generate -i Tools/APIWrapperGen/swagger.json -l python -t Tools/APIWrapperGen/Templates/python/ -o ./app/client -c Tools/APIWrapperGen/config.json
    - cd app/client/py4heappe
    - zip -r ../../../APIWrapperGen.zip .
  tags:
    - Docker
    - Centos9
    - IT4I_Network
  artifacts:
    paths:
      - APIWrapperGen.zip
    expire_in: 1 days
