# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AdminSubmittedJobInfoExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'state': 'JobStateExt',
        'state_source': 'JobStateSourceExt',
        'state_updated_at': 'datetime',
        'creation_time': 'datetime',
        'submit_time': 'datetime',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'total_allocated_time': 'float',
        'submitter': 'AdminSubmitterInfoExt',
        'submitter_group': 'str',
        'cluster_username': 'str',
        'cluster_authentication_type': 'ClusterAuthenticationCredentialsAuthTypeExt',
        'project_id': 'int',
        'project_name': 'str',
        'sub_project_id': 'int',
        'sub_project_identifier': 'str',
        'cluster_id': 'int',
        'cluster_name': 'str',
        'reservation': 'str',
        'tasks': 'list[AdminTaskInfoExt]'
    }

    attribute_map = {
        'id': 'Id',
        'name': 'Name',
        'state': 'State',
        'state_source': 'StateSource',
        'state_updated_at': 'StateUpdatedAt',
        'creation_time': 'CreationTime',
        'submit_time': 'SubmitTime',
        'start_time': 'StartTime',
        'end_time': 'EndTime',
        'total_allocated_time': 'TotalAllocatedTime',
        'submitter': 'Submitter',
        'submitter_group': 'SubmitterGroup',
        'cluster_username': 'ClusterUsername',
        'cluster_authentication_type': 'ClusterAuthenticationType',
        'project_id': 'ProjectId',
        'project_name': 'ProjectName',
        'sub_project_id': 'SubProjectId',
        'sub_project_identifier': 'SubProjectIdentifier',
        'cluster_id': 'ClusterId',
        'cluster_name': 'ClusterName',
        'reservation': 'Reservation',
        'tasks': 'Tasks'
    }

    def __init__(self, id=None, name=None, state=None, state_source=None, state_updated_at=None, creation_time=None, submit_time=None, start_time=None, end_time=None, total_allocated_time=None, submitter=None, submitter_group=None, cluster_username=None, cluster_authentication_type=None, project_id=None, project_name=None, sub_project_id=None, sub_project_identifier=None, cluster_id=None, cluster_name=None, reservation=None, tasks=None):  # noqa: E501
        """AdminSubmittedJobInfoExt - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._state = None
        self._state_source = None
        self._state_updated_at = None
        self._creation_time = None
        self._submit_time = None
        self._start_time = None
        self._end_time = None
        self._total_allocated_time = None
        self._submitter = None
        self._submitter_group = None
        self._cluster_username = None
        self._cluster_authentication_type = None
        self._project_id = None
        self._project_name = None
        self._sub_project_id = None
        self._sub_project_identifier = None
        self._cluster_id = None
        self._cluster_name = None
        self._reservation = None
        self._tasks = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if state is not None:
            self.state = state
        if state_source is not None:
            self.state_source = state_source
        if state_updated_at is not None:
            self.state_updated_at = state_updated_at
        if creation_time is not None:
            self.creation_time = creation_time
        if submit_time is not None:
            self.submit_time = submit_time
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if total_allocated_time is not None:
            self.total_allocated_time = total_allocated_time
        if submitter is not None:
            self.submitter = submitter
        if submitter_group is not None:
            self.submitter_group = submitter_group
        if cluster_username is not None:
            self.cluster_username = cluster_username
        if cluster_authentication_type is not None:
            self.cluster_authentication_type = cluster_authentication_type
        if project_id is not None:
            self.project_id = project_id
        if project_name is not None:
            self.project_name = project_name
        if sub_project_id is not None:
            self.sub_project_id = sub_project_id
        if sub_project_identifier is not None:
            self.sub_project_identifier = sub_project_identifier
        if cluster_id is not None:
            self.cluster_id = cluster_id
        if cluster_name is not None:
            self.cluster_name = cluster_name
        if reservation is not None:
            self.reservation = reservation
        if tasks is not None:
            self.tasks = tasks

    @property
    def id(self):
        """Gets the id of this AdminSubmittedJobInfoExt.  # noqa: E501

        Id  # noqa: E501

        :return: The id of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AdminSubmittedJobInfoExt.

        Id  # noqa: E501

        :param id: The id of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this AdminSubmittedJobInfoExt.  # noqa: E501

        Name  # noqa: E501

        :return: The name of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AdminSubmittedJobInfoExt.

        Name  # noqa: E501

        :param name: The name of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def state(self):
        """Gets the state of this AdminSubmittedJobInfoExt.  # noqa: E501


        :return: The state of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: JobStateExt
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this AdminSubmittedJobInfoExt.


        :param state: The state of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: JobStateExt
        """

        self._state = state

    @property
    def state_source(self):
        """Gets the state_source of this AdminSubmittedJobInfoExt.  # noqa: E501


        :return: The state_source of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: JobStateSourceExt
        """
        return self._state_source

    @state_source.setter
    def state_source(self, state_source):
        """Sets the state_source of this AdminSubmittedJobInfoExt.


        :param state_source: The state_source of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: JobStateSourceExt
        """

        self._state_source = state_source

    @property
    def state_updated_at(self):
        """Gets the state_updated_at of this AdminSubmittedJobInfoExt.  # noqa: E501

        Timestamp of last state update  # noqa: E501

        :return: The state_updated_at of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._state_updated_at

    @state_updated_at.setter
    def state_updated_at(self, state_updated_at):
        """Sets the state_updated_at of this AdminSubmittedJobInfoExt.

        Timestamp of last state update  # noqa: E501

        :param state_updated_at: The state_updated_at of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: datetime
        """

        self._state_updated_at = state_updated_at

    @property
    def creation_time(self):
        """Gets the creation_time of this AdminSubmittedJobInfoExt.  # noqa: E501

        Creation time  # noqa: E501

        :return: The creation_time of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """Sets the creation_time of this AdminSubmittedJobInfoExt.

        Creation time  # noqa: E501

        :param creation_time: The creation_time of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: datetime
        """

        self._creation_time = creation_time

    @property
    def submit_time(self):
        """Gets the submit_time of this AdminSubmittedJobInfoExt.  # noqa: E501

        Submit time  # noqa: E501

        :return: The submit_time of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._submit_time

    @submit_time.setter
    def submit_time(self, submit_time):
        """Sets the submit_time of this AdminSubmittedJobInfoExt.

        Submit time  # noqa: E501

        :param submit_time: The submit_time of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: datetime
        """

        self._submit_time = submit_time

    @property
    def start_time(self):
        """Gets the start_time of this AdminSubmittedJobInfoExt.  # noqa: E501

        Start time  # noqa: E501

        :return: The start_time of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this AdminSubmittedJobInfoExt.

        Start time  # noqa: E501

        :param start_time: The start_time of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this AdminSubmittedJobInfoExt.  # noqa: E501

        End time  # noqa: E501

        :return: The end_time of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this AdminSubmittedJobInfoExt.

        End time  # noqa: E501

        :param end_time: The end_time of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    @property
    def total_allocated_time(self):
        """Gets the total_allocated_time of this AdminSubmittedJobInfoExt.  # noqa: E501

        Total allocation time  # noqa: E501

        :return: The total_allocated_time of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: float
        """
        return self._total_allocated_time

    @total_allocated_time.setter
    def total_allocated_time(self, total_allocated_time):
        """Sets the total_allocated_time of this AdminSubmittedJobInfoExt.

        Total allocation time  # noqa: E501

        :param total_allocated_time: The total_allocated_time of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: float
        """

        self._total_allocated_time = total_allocated_time

    @property
    def submitter(self):
        """Gets the submitter of this AdminSubmittedJobInfoExt.  # noqa: E501


        :return: The submitter of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: AdminSubmitterInfoExt
        """
        return self._submitter

    @submitter.setter
    def submitter(self, submitter):
        """Sets the submitter of this AdminSubmittedJobInfoExt.


        :param submitter: The submitter of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: AdminSubmitterInfoExt
        """

        self._submitter = submitter

    @property
    def submitter_group(self):
        """Gets the submitter_group of this AdminSubmittedJobInfoExt.  # noqa: E501

        Submitter group name  # noqa: E501

        :return: The submitter_group of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._submitter_group

    @submitter_group.setter
    def submitter_group(self, submitter_group):
        """Sets the submitter_group of this AdminSubmittedJobInfoExt.

        Submitter group name  # noqa: E501

        :param submitter_group: The submitter_group of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: str
        """

        self._submitter_group = submitter_group

    @property
    def cluster_username(self):
        """Gets the cluster_username of this AdminSubmittedJobInfoExt.  # noqa: E501

        Cluster username used internally on HPC cluster  # noqa: E501

        :return: The cluster_username of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._cluster_username

    @cluster_username.setter
    def cluster_username(self, cluster_username):
        """Sets the cluster_username of this AdminSubmittedJobInfoExt.

        Cluster username used internally on HPC cluster  # noqa: E501

        :param cluster_username: The cluster_username of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: str
        """

        self._cluster_username = cluster_username

    @property
    def cluster_authentication_type(self):
        """Gets the cluster_authentication_type of this AdminSubmittedJobInfoExt.  # noqa: E501


        :return: The cluster_authentication_type of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: ClusterAuthenticationCredentialsAuthTypeExt
        """
        return self._cluster_authentication_type

    @cluster_authentication_type.setter
    def cluster_authentication_type(self, cluster_authentication_type):
        """Sets the cluster_authentication_type of this AdminSubmittedJobInfoExt.


        :param cluster_authentication_type: The cluster_authentication_type of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: ClusterAuthenticationCredentialsAuthTypeExt
        """

        self._cluster_authentication_type = cluster_authentication_type

    @property
    def project_id(self):
        """Gets the project_id of this AdminSubmittedJobInfoExt.  # noqa: E501

        Project ID  # noqa: E501

        :return: The project_id of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this AdminSubmittedJobInfoExt.

        Project ID  # noqa: E501

        :param project_id: The project_id of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def project_name(self):
        """Gets the project_name of this AdminSubmittedJobInfoExt.  # noqa: E501

        Project name  # noqa: E501

        :return: The project_name of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this AdminSubmittedJobInfoExt.

        Project name  # noqa: E501

        :param project_name: The project_name of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def sub_project_id(self):
        """Gets the sub_project_id of this AdminSubmittedJobInfoExt.  # noqa: E501

        SubProject ID  # noqa: E501

        :return: The sub_project_id of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._sub_project_id

    @sub_project_id.setter
    def sub_project_id(self, sub_project_id):
        """Sets the sub_project_id of this AdminSubmittedJobInfoExt.

        SubProject ID  # noqa: E501

        :param sub_project_id: The sub_project_id of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: int
        """

        self._sub_project_id = sub_project_id

    @property
    def sub_project_identifier(self):
        """Gets the sub_project_identifier of this AdminSubmittedJobInfoExt.  # noqa: E501

        SubProject identifier  # noqa: E501

        :return: The sub_project_identifier of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._sub_project_identifier

    @sub_project_identifier.setter
    def sub_project_identifier(self, sub_project_identifier):
        """Sets the sub_project_identifier of this AdminSubmittedJobInfoExt.

        SubProject identifier  # noqa: E501

        :param sub_project_identifier: The sub_project_identifier of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: str
        """

        self._sub_project_identifier = sub_project_identifier

    @property
    def cluster_id(self):
        """Gets the cluster_id of this AdminSubmittedJobInfoExt.  # noqa: E501

        Cluster ID  # noqa: E501

        :return: The cluster_id of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this AdminSubmittedJobInfoExt.

        Cluster ID  # noqa: E501

        :param cluster_id: The cluster_id of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: int
        """

        self._cluster_id = cluster_id

    @property
    def cluster_name(self):
        """Gets the cluster_name of this AdminSubmittedJobInfoExt.  # noqa: E501

        Cluster name  # noqa: E501

        :return: The cluster_name of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._cluster_name

    @cluster_name.setter
    def cluster_name(self, cluster_name):
        """Sets the cluster_name of this AdminSubmittedJobInfoExt.

        Cluster name  # noqa: E501

        :param cluster_name: The cluster_name of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: str
        """

        self._cluster_name = cluster_name

    @property
    def reservation(self):
        """Gets the reservation of this AdminSubmittedJobInfoExt.  # noqa: E501

        HPC reservation string  # noqa: E501

        :return: The reservation of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._reservation

    @reservation.setter
    def reservation(self, reservation):
        """Sets the reservation of this AdminSubmittedJobInfoExt.

        HPC reservation string  # noqa: E501

        :param reservation: The reservation of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: str
        """

        self._reservation = reservation

    @property
    def tasks(self):
        """Gets the tasks of this AdminSubmittedJobInfoExt.  # noqa: E501

        Array of tasks  # noqa: E501

        :return: The tasks of this AdminSubmittedJobInfoExt.  # noqa: E501
        :rtype: list[AdminTaskInfoExt]
        """
        return self._tasks

    @tasks.setter
    def tasks(self, tasks):
        """Sets the tasks of this AdminSubmittedJobInfoExt.

        Array of tasks  # noqa: E501

        :param tasks: The tasks of this AdminSubmittedJobInfoExt.  # noqa: E501
        :type: list[AdminTaskInfoExt]
        """

        self._tasks = tasks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdminSubmittedJobInfoExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminSubmittedJobInfoExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
