# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AdminSubmitterInfoExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'username': 'str',
        'email': 'str',
        'idp_sid': 'str'
    }

    attribute_map = {
        'id': 'Id',
        'username': 'Username',
        'email': 'Email',
        'idp_sid': 'IdpSid'
    }

    def __init__(self, id=None, username=None, email=None, idp_sid=None):  # noqa: E501
        """AdminSubmitterInfoExt - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._username = None
        self._email = None
        self._idp_sid = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if username is not None:
            self.username = username
        if email is not None:
            self.email = email
        if idp_sid is not None:
            self.idp_sid = idp_sid

    @property
    def id(self):
        """Gets the id of this AdminSubmitterInfoExt.  # noqa: E501

        User Id  # noqa: E501

        :return: The id of this AdminSubmitterInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AdminSubmitterInfoExt.

        User Id  # noqa: E501

        :param id: The id of this AdminSubmitterInfoExt.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def username(self):
        """Gets the username of this AdminSubmitterInfoExt.  # noqa: E501

        Username  # noqa: E501

        :return: The username of this AdminSubmitterInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this AdminSubmitterInfoExt.

        Username  # noqa: E501

        :param username: The username of this AdminSubmitterInfoExt.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def email(self):
        """Gets the email of this AdminSubmitterInfoExt.  # noqa: E501

        Email  # noqa: E501

        :return: The email of this AdminSubmitterInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this AdminSubmitterInfoExt.

        Email  # noqa: E501

        :param email: The email of this AdminSubmitterInfoExt.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def idp_sid(self):
        """Gets the idp_sid of this AdminSubmitterInfoExt.  # noqa: E501

        Identity Provider Subject ID (e.g. Keycloak / OIDC SID)  # noqa: E501

        :return: The idp_sid of this AdminSubmitterInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._idp_sid

    @idp_sid.setter
    def idp_sid(self, idp_sid):
        """Sets the idp_sid of this AdminSubmitterInfoExt.

        Identity Provider Subject ID (e.g. Keycloak / OIDC SID)  # noqa: E501

        :param idp_sid: The idp_sid of this AdminSubmitterInfoExt.  # noqa: E501
        :type: str
        """

        self._idp_sid = idp_sid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdminSubmitterInfoExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminSubmitterInfoExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
