# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AdminTaskInfoExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'state': 'TaskStateExt',
        'state_source': 'JobStateSourceExt',
        'state_updated_at': 'datetime',
        'priority': 'TaskPriorityExt',
        'allocated_time': 'float',
        'allocated_core_ids': 'list[str]',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'node_type': 'ClusterNodeTypeForTaskExt',
        'error_message': 'str',
        'cpu_hyper_threading': 'bool',
        'reason': 'str',
        'min_cores': 'int',
        'max_cores': 'int',
        'gpu_cores': 'int',
        'gpu_nodes': 'int',
        'walltime_limit': 'int',
        'memory': 'int',
        'memory_per_cpu': 'int',
        'memory_per_gpu': 'int',
        'placement_policy': 'str',
        'is_exclusive': 'bool',
        'is_rerunnable': 'bool',
        'job_arrays': 'str',
        'standard_input_file': 'str',
        'standard_output_file': 'str',
        'standard_error_file': 'str',
        'cluster_task_subdirectory': 'str',
        'command_template_id': 'int',
        'template_parameter_values': 'list[CommandTemplateParameterValueExt]',
        'environment_variables': 'list[EnvironmentVariableExt]'
    }

    attribute_map = {
        'id': 'Id',
        'name': 'Name',
        'state': 'State',
        'state_source': 'StateSource',
        'state_updated_at': 'StateUpdatedAt',
        'priority': 'Priority',
        'allocated_time': 'AllocatedTime',
        'allocated_core_ids': 'AllocatedCoreIds',
        'start_time': 'StartTime',
        'end_time': 'EndTime',
        'node_type': 'NodeType',
        'error_message': 'ErrorMessage',
        'cpu_hyper_threading': 'CpuHyperThreading',
        'reason': 'Reason',
        'min_cores': 'MinCores',
        'max_cores': 'MaxCores',
        'gpu_cores': 'GpuCores',
        'gpu_nodes': 'GpuNodes',
        'walltime_limit': 'WalltimeLimit',
        'memory': 'Memory',
        'memory_per_cpu': 'MemoryPerCPU',
        'memory_per_gpu': 'MemoryPerGPU',
        'placement_policy': 'PlacementPolicy',
        'is_exclusive': 'IsExclusive',
        'is_rerunnable': 'IsRerunnable',
        'job_arrays': 'JobArrays',
        'standard_input_file': 'StandardInputFile',
        'standard_output_file': 'StandardOutputFile',
        'standard_error_file': 'StandardErrorFile',
        'cluster_task_subdirectory': 'ClusterTaskSubdirectory',
        'command_template_id': 'CommandTemplateId',
        'template_parameter_values': 'TemplateParameterValues',
        'environment_variables': 'EnvironmentVariables'
    }

    def __init__(self, id=None, name=None, state=None, state_source=None, state_updated_at=None, priority=None, allocated_time=None, allocated_core_ids=None, start_time=None, end_time=None, node_type=None, error_message=None, cpu_hyper_threading=None, reason=None, min_cores=None, max_cores=None, gpu_cores=None, gpu_nodes=None, walltime_limit=None, memory=None, memory_per_cpu=None, memory_per_gpu=None, placement_policy=None, is_exclusive=None, is_rerunnable=None, job_arrays=None, standard_input_file=None, standard_output_file=None, standard_error_file=None, cluster_task_subdirectory=None, command_template_id=None, template_parameter_values=None, environment_variables=None):  # noqa: E501
        """AdminTaskInfoExt - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._state = None
        self._state_source = None
        self._state_updated_at = None
        self._priority = None
        self._allocated_time = None
        self._allocated_core_ids = None
        self._start_time = None
        self._end_time = None
        self._node_type = None
        self._error_message = None
        self._cpu_hyper_threading = None
        self._reason = None
        self._min_cores = None
        self._max_cores = None
        self._gpu_cores = None
        self._gpu_nodes = None
        self._walltime_limit = None
        self._memory = None
        self._memory_per_cpu = None
        self._memory_per_gpu = None
        self._placement_policy = None
        self._is_exclusive = None
        self._is_rerunnable = None
        self._job_arrays = None
        self._standard_input_file = None
        self._standard_output_file = None
        self._standard_error_file = None
        self._cluster_task_subdirectory = None
        self._command_template_id = None
        self._template_parameter_values = None
        self._environment_variables = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if state is not None:
            self.state = state
        if state_source is not None:
            self.state_source = state_source
        if state_updated_at is not None:
            self.state_updated_at = state_updated_at
        if priority is not None:
            self.priority = priority
        if allocated_time is not None:
            self.allocated_time = allocated_time
        if allocated_core_ids is not None:
            self.allocated_core_ids = allocated_core_ids
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if node_type is not None:
            self.node_type = node_type
        if error_message is not None:
            self.error_message = error_message
        if cpu_hyper_threading is not None:
            self.cpu_hyper_threading = cpu_hyper_threading
        if reason is not None:
            self.reason = reason
        if min_cores is not None:
            self.min_cores = min_cores
        if max_cores is not None:
            self.max_cores = max_cores
        if gpu_cores is not None:
            self.gpu_cores = gpu_cores
        if gpu_nodes is not None:
            self.gpu_nodes = gpu_nodes
        if walltime_limit is not None:
            self.walltime_limit = walltime_limit
        if memory is not None:
            self.memory = memory
        if memory_per_cpu is not None:
            self.memory_per_cpu = memory_per_cpu
        if memory_per_gpu is not None:
            self.memory_per_gpu = memory_per_gpu
        if placement_policy is not None:
            self.placement_policy = placement_policy
        if is_exclusive is not None:
            self.is_exclusive = is_exclusive
        if is_rerunnable is not None:
            self.is_rerunnable = is_rerunnable
        if job_arrays is not None:
            self.job_arrays = job_arrays
        if standard_input_file is not None:
            self.standard_input_file = standard_input_file
        if standard_output_file is not None:
            self.standard_output_file = standard_output_file
        if standard_error_file is not None:
            self.standard_error_file = standard_error_file
        if cluster_task_subdirectory is not None:
            self.cluster_task_subdirectory = cluster_task_subdirectory
        if command_template_id is not None:
            self.command_template_id = command_template_id
        if template_parameter_values is not None:
            self.template_parameter_values = template_parameter_values
        if environment_variables is not None:
            self.environment_variables = environment_variables

    @property
    def id(self):
        """Gets the id of this AdminTaskInfoExt.  # noqa: E501

        Id  # noqa: E501

        :return: The id of this AdminTaskInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AdminTaskInfoExt.

        Id  # noqa: E501

        :param id: The id of this AdminTaskInfoExt.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this AdminTaskInfoExt.  # noqa: E501

        Name  # noqa: E501

        :return: The name of this AdminTaskInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AdminTaskInfoExt.

        Name  # noqa: E501

        :param name: The name of this AdminTaskInfoExt.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def state(self):
        """Gets the state of this AdminTaskInfoExt.  # noqa: E501


        :return: The state of this AdminTaskInfoExt.  # noqa: E501
        :rtype: TaskStateExt
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this AdminTaskInfoExt.


        :param state: The state of this AdminTaskInfoExt.  # noqa: E501
        :type: TaskStateExt
        """

        self._state = state

    @property
    def state_source(self):
        """Gets the state_source of this AdminTaskInfoExt.  # noqa: E501


        :return: The state_source of this AdminTaskInfoExt.  # noqa: E501
        :rtype: JobStateSourceExt
        """
        return self._state_source

    @state_source.setter
    def state_source(self, state_source):
        """Sets the state_source of this AdminTaskInfoExt.


        :param state_source: The state_source of this AdminTaskInfoExt.  # noqa: E501
        :type: JobStateSourceExt
        """

        self._state_source = state_source

    @property
    def state_updated_at(self):
        """Gets the state_updated_at of this AdminTaskInfoExt.  # noqa: E501

        Timestamp of last state update  # noqa: E501

        :return: The state_updated_at of this AdminTaskInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._state_updated_at

    @state_updated_at.setter
    def state_updated_at(self, state_updated_at):
        """Sets the state_updated_at of this AdminTaskInfoExt.

        Timestamp of last state update  # noqa: E501

        :param state_updated_at: The state_updated_at of this AdminTaskInfoExt.  # noqa: E501
        :type: datetime
        """

        self._state_updated_at = state_updated_at

    @property
    def priority(self):
        """Gets the priority of this AdminTaskInfoExt.  # noqa: E501


        :return: The priority of this AdminTaskInfoExt.  # noqa: E501
        :rtype: TaskPriorityExt
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this AdminTaskInfoExt.


        :param priority: The priority of this AdminTaskInfoExt.  # noqa: E501
        :type: TaskPriorityExt
        """

        self._priority = priority

    @property
    def allocated_time(self):
        """Gets the allocated_time of this AdminTaskInfoExt.  # noqa: E501

        Allocated time  # noqa: E501

        :return: The allocated_time of this AdminTaskInfoExt.  # noqa: E501
        :rtype: float
        """
        return self._allocated_time

    @allocated_time.setter
    def allocated_time(self, allocated_time):
        """Sets the allocated_time of this AdminTaskInfoExt.

        Allocated time  # noqa: E501

        :param allocated_time: The allocated_time of this AdminTaskInfoExt.  # noqa: E501
        :type: float
        """

        self._allocated_time = allocated_time

    @property
    def allocated_core_ids(self):
        """Gets the allocated_core_ids of this AdminTaskInfoExt.  # noqa: E501

        Array of allocated core ids  # noqa: E501

        :return: The allocated_core_ids of this AdminTaskInfoExt.  # noqa: E501
        :rtype: list[str]
        """
        return self._allocated_core_ids

    @allocated_core_ids.setter
    def allocated_core_ids(self, allocated_core_ids):
        """Sets the allocated_core_ids of this AdminTaskInfoExt.

        Array of allocated core ids  # noqa: E501

        :param allocated_core_ids: The allocated_core_ids of this AdminTaskInfoExt.  # noqa: E501
        :type: list[str]
        """

        self._allocated_core_ids = allocated_core_ids

    @property
    def start_time(self):
        """Gets the start_time of this AdminTaskInfoExt.  # noqa: E501

        Start time  # noqa: E501

        :return: The start_time of this AdminTaskInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this AdminTaskInfoExt.

        Start time  # noqa: E501

        :param start_time: The start_time of this AdminTaskInfoExt.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this AdminTaskInfoExt.  # noqa: E501

        End time  # noqa: E501

        :return: The end_time of this AdminTaskInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this AdminTaskInfoExt.

        End time  # noqa: E501

        :param end_time: The end_time of this AdminTaskInfoExt.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    @property
    def node_type(self):
        """Gets the node_type of this AdminTaskInfoExt.  # noqa: E501


        :return: The node_type of this AdminTaskInfoExt.  # noqa: E501
        :rtype: ClusterNodeTypeForTaskExt
        """
        return self._node_type

    @node_type.setter
    def node_type(self, node_type):
        """Sets the node_type of this AdminTaskInfoExt.


        :param node_type: The node_type of this AdminTaskInfoExt.  # noqa: E501
        :type: ClusterNodeTypeForTaskExt
        """

        self._node_type = node_type

    @property
    def error_message(self):
        """Gets the error_message of this AdminTaskInfoExt.  # noqa: E501

        Error message  # noqa: E501

        :return: The error_message of this AdminTaskInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this AdminTaskInfoExt.

        Error message  # noqa: E501

        :param error_message: The error_message of this AdminTaskInfoExt.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def cpu_hyper_threading(self):
        """Gets the cpu_hyper_threading of this AdminTaskInfoExt.  # noqa: E501

        Cpu hyper threading  # noqa: E501

        :return: The cpu_hyper_threading of this AdminTaskInfoExt.  # noqa: E501
        :rtype: bool
        """
        return self._cpu_hyper_threading

    @cpu_hyper_threading.setter
    def cpu_hyper_threading(self, cpu_hyper_threading):
        """Sets the cpu_hyper_threading of this AdminTaskInfoExt.

        Cpu hyper threading  # noqa: E501

        :param cpu_hyper_threading: The cpu_hyper_threading of this AdminTaskInfoExt.  # noqa: E501
        :type: bool
        """

        self._cpu_hyper_threading = cpu_hyper_threading

    @property
    def reason(self):
        """Gets the reason of this AdminTaskInfoExt.  # noqa: E501

        Reason (parsed from scheduler, e.g. SLURM)  # noqa: E501

        :return: The reason of this AdminTaskInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this AdminTaskInfoExt.

        Reason (parsed from scheduler, e.g. SLURM)  # noqa: E501

        :param reason: The reason of this AdminTaskInfoExt.  # noqa: E501
        :type: str
        """

        self._reason = reason

    @property
    def min_cores(self):
        """Gets the min_cores of this AdminTaskInfoExt.  # noqa: E501

        Minimum CPU cores  # noqa: E501

        :return: The min_cores of this AdminTaskInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._min_cores

    @min_cores.setter
    def min_cores(self, min_cores):
        """Sets the min_cores of this AdminTaskInfoExt.

        Minimum CPU cores  # noqa: E501

        :param min_cores: The min_cores of this AdminTaskInfoExt.  # noqa: E501
        :type: int
        """

        self._min_cores = min_cores

    @property
    def max_cores(self):
        """Gets the max_cores of this AdminTaskInfoExt.  # noqa: E501

        Maximum CPU cores  # noqa: E501

        :return: The max_cores of this AdminTaskInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._max_cores

    @max_cores.setter
    def max_cores(self, max_cores):
        """Sets the max_cores of this AdminTaskInfoExt.

        Maximum CPU cores  # noqa: E501

        :param max_cores: The max_cores of this AdminTaskInfoExt.  # noqa: E501
        :type: int
        """

        self._max_cores = max_cores

    @property
    def gpu_cores(self):
        """Gets the gpu_cores of this AdminTaskInfoExt.  # noqa: E501

        GPU cores  # noqa: E501

        :return: The gpu_cores of this AdminTaskInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._gpu_cores

    @gpu_cores.setter
    def gpu_cores(self, gpu_cores):
        """Sets the gpu_cores of this AdminTaskInfoExt.

        GPU cores  # noqa: E501

        :param gpu_cores: The gpu_cores of this AdminTaskInfoExt.  # noqa: E501
        :type: int
        """

        self._gpu_cores = gpu_cores

    @property
    def gpu_nodes(self):
        """Gets the gpu_nodes of this AdminTaskInfoExt.  # noqa: E501

        GPU nodes  # noqa: E501

        :return: The gpu_nodes of this AdminTaskInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._gpu_nodes

    @gpu_nodes.setter
    def gpu_nodes(self, gpu_nodes):
        """Sets the gpu_nodes of this AdminTaskInfoExt.

        GPU nodes  # noqa: E501

        :param gpu_nodes: The gpu_nodes of this AdminTaskInfoExt.  # noqa: E501
        :type: int
        """

        self._gpu_nodes = gpu_nodes

    @property
    def walltime_limit(self):
        """Gets the walltime_limit of this AdminTaskInfoExt.  # noqa: E501

        Walltime limit  # noqa: E501

        :return: The walltime_limit of this AdminTaskInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._walltime_limit

    @walltime_limit.setter
    def walltime_limit(self, walltime_limit):
        """Sets the walltime_limit of this AdminTaskInfoExt.

        Walltime limit  # noqa: E501

        :param walltime_limit: The walltime_limit of this AdminTaskInfoExt.  # noqa: E501
        :type: int
        """

        self._walltime_limit = walltime_limit

    @property
    def memory(self):
        """Gets the memory of this AdminTaskInfoExt.  # noqa: E501

        Memory  # noqa: E501

        :return: The memory of this AdminTaskInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._memory

    @memory.setter
    def memory(self, memory):
        """Sets the memory of this AdminTaskInfoExt.

        Memory  # noqa: E501

        :param memory: The memory of this AdminTaskInfoExt.  # noqa: E501
        :type: int
        """

        self._memory = memory

    @property
    def memory_per_cpu(self):
        """Gets the memory_per_cpu of this AdminTaskInfoExt.  # noqa: E501

        Memory per CPU  # noqa: E501

        :return: The memory_per_cpu of this AdminTaskInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._memory_per_cpu

    @memory_per_cpu.setter
    def memory_per_cpu(self, memory_per_cpu):
        """Sets the memory_per_cpu of this AdminTaskInfoExt.

        Memory per CPU  # noqa: E501

        :param memory_per_cpu: The memory_per_cpu of this AdminTaskInfoExt.  # noqa: E501
        :type: int
        """

        self._memory_per_cpu = memory_per_cpu

    @property
    def memory_per_gpu(self):
        """Gets the memory_per_gpu of this AdminTaskInfoExt.  # noqa: E501

        Memory per GPU  # noqa: E501

        :return: The memory_per_gpu of this AdminTaskInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._memory_per_gpu

    @memory_per_gpu.setter
    def memory_per_gpu(self, memory_per_gpu):
        """Sets the memory_per_gpu of this AdminTaskInfoExt.

        Memory per GPU  # noqa: E501

        :param memory_per_gpu: The memory_per_gpu of this AdminTaskInfoExt.  # noqa: E501
        :type: int
        """

        self._memory_per_gpu = memory_per_gpu

    @property
    def placement_policy(self):
        """Gets the placement_policy of this AdminTaskInfoExt.  # noqa: E501

        Placement policy  # noqa: E501

        :return: The placement_policy of this AdminTaskInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._placement_policy

    @placement_policy.setter
    def placement_policy(self, placement_policy):
        """Sets the placement_policy of this AdminTaskInfoExt.

        Placement policy  # noqa: E501

        :param placement_policy: The placement_policy of this AdminTaskInfoExt.  # noqa: E501
        :type: str
        """

        self._placement_policy = placement_policy

    @property
    def is_exclusive(self):
        """Gets the is_exclusive of this AdminTaskInfoExt.  # noqa: E501

        Is exclusive  # noqa: E501

        :return: The is_exclusive of this AdminTaskInfoExt.  # noqa: E501
        :rtype: bool
        """
        return self._is_exclusive

    @is_exclusive.setter
    def is_exclusive(self, is_exclusive):
        """Sets the is_exclusive of this AdminTaskInfoExt.

        Is exclusive  # noqa: E501

        :param is_exclusive: The is_exclusive of this AdminTaskInfoExt.  # noqa: E501
        :type: bool
        """

        self._is_exclusive = is_exclusive

    @property
    def is_rerunnable(self):
        """Gets the is_rerunnable of this AdminTaskInfoExt.  # noqa: E501

        Is rerunnable  # noqa: E501

        :return: The is_rerunnable of this AdminTaskInfoExt.  # noqa: E501
        :rtype: bool
        """
        return self._is_rerunnable

    @is_rerunnable.setter
    def is_rerunnable(self, is_rerunnable):
        """Sets the is_rerunnable of this AdminTaskInfoExt.

        Is rerunnable  # noqa: E501

        :param is_rerunnable: The is_rerunnable of this AdminTaskInfoExt.  # noqa: E501
        :type: bool
        """

        self._is_rerunnable = is_rerunnable

    @property
    def job_arrays(self):
        """Gets the job_arrays of this AdminTaskInfoExt.  # noqa: E501

        Job arrays  # noqa: E501

        :return: The job_arrays of this AdminTaskInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._job_arrays

    @job_arrays.setter
    def job_arrays(self, job_arrays):
        """Sets the job_arrays of this AdminTaskInfoExt.

        Job arrays  # noqa: E501

        :param job_arrays: The job_arrays of this AdminTaskInfoExt.  # noqa: E501
        :type: str
        """

        self._job_arrays = job_arrays

    @property
    def standard_input_file(self):
        """Gets the standard_input_file of this AdminTaskInfoExt.  # noqa: E501

        Standard input file  # noqa: E501

        :return: The standard_input_file of this AdminTaskInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._standard_input_file

    @standard_input_file.setter
    def standard_input_file(self, standard_input_file):
        """Sets the standard_input_file of this AdminTaskInfoExt.

        Standard input file  # noqa: E501

        :param standard_input_file: The standard_input_file of this AdminTaskInfoExt.  # noqa: E501
        :type: str
        """

        self._standard_input_file = standard_input_file

    @property
    def standard_output_file(self):
        """Gets the standard_output_file of this AdminTaskInfoExt.  # noqa: E501

        Standard output file  # noqa: E501

        :return: The standard_output_file of this AdminTaskInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._standard_output_file

    @standard_output_file.setter
    def standard_output_file(self, standard_output_file):
        """Sets the standard_output_file of this AdminTaskInfoExt.

        Standard output file  # noqa: E501

        :param standard_output_file: The standard_output_file of this AdminTaskInfoExt.  # noqa: E501
        :type: str
        """

        self._standard_output_file = standard_output_file

    @property
    def standard_error_file(self):
        """Gets the standard_error_file of this AdminTaskInfoExt.  # noqa: E501

        Standard error file  # noqa: E501

        :return: The standard_error_file of this AdminTaskInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._standard_error_file

    @standard_error_file.setter
    def standard_error_file(self, standard_error_file):
        """Sets the standard_error_file of this AdminTaskInfoExt.

        Standard error file  # noqa: E501

        :param standard_error_file: The standard_error_file of this AdminTaskInfoExt.  # noqa: E501
        :type: str
        """

        self._standard_error_file = standard_error_file

    @property
    def cluster_task_subdirectory(self):
        """Gets the cluster_task_subdirectory of this AdminTaskInfoExt.  # noqa: E501

        Cluster task subdirectory  # noqa: E501

        :return: The cluster_task_subdirectory of this AdminTaskInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._cluster_task_subdirectory

    @cluster_task_subdirectory.setter
    def cluster_task_subdirectory(self, cluster_task_subdirectory):
        """Sets the cluster_task_subdirectory of this AdminTaskInfoExt.

        Cluster task subdirectory  # noqa: E501

        :param cluster_task_subdirectory: The cluster_task_subdirectory of this AdminTaskInfoExt.  # noqa: E501
        :type: str
        """

        self._cluster_task_subdirectory = cluster_task_subdirectory

    @property
    def command_template_id(self):
        """Gets the command_template_id of this AdminTaskInfoExt.  # noqa: E501

        Command template id  # noqa: E501

        :return: The command_template_id of this AdminTaskInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._command_template_id

    @command_template_id.setter
    def command_template_id(self, command_template_id):
        """Sets the command_template_id of this AdminTaskInfoExt.

        Command template id  # noqa: E501

        :param command_template_id: The command_template_id of this AdminTaskInfoExt.  # noqa: E501
        :type: int
        """

        self._command_template_id = command_template_id

    @property
    def template_parameter_values(self):
        """Gets the template_parameter_values of this AdminTaskInfoExt.  # noqa: E501

        Command template parameter values submitted by user  # noqa: E501

        :return: The template_parameter_values of this AdminTaskInfoExt.  # noqa: E501
        :rtype: list[CommandTemplateParameterValueExt]
        """
        return self._template_parameter_values

    @template_parameter_values.setter
    def template_parameter_values(self, template_parameter_values):
        """Sets the template_parameter_values of this AdminTaskInfoExt.

        Command template parameter values submitted by user  # noqa: E501

        :param template_parameter_values: The template_parameter_values of this AdminTaskInfoExt.  # noqa: E501
        :type: list[CommandTemplateParameterValueExt]
        """

        self._template_parameter_values = template_parameter_values

    @property
    def environment_variables(self):
        """Gets the environment_variables of this AdminTaskInfoExt.  # noqa: E501

        Environment variables  # noqa: E501

        :return: The environment_variables of this AdminTaskInfoExt.  # noqa: E501
        :rtype: list[EnvironmentVariableExt]
        """
        return self._environment_variables

    @environment_variables.setter
    def environment_variables(self, environment_variables):
        """Sets the environment_variables of this AdminTaskInfoExt.

        Environment variables  # noqa: E501

        :param environment_variables: The environment_variables of this AdminTaskInfoExt.  # noqa: E501
        :type: list[EnvironmentVariableExt]
        """

        self._environment_variables = environment_variables

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdminTaskInfoExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminTaskInfoExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
