# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssignAdaptorUserToUserGroupModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_code': 'str',
        'username': 'str',
        'user_group_id': 'int',
        'role': 'AdaptorUserRoleType'
    }

    attribute_map = {
        'session_code': 'SessionCode',
        'username': 'Username',
        'user_group_id': 'UserGroupId',
        'role': 'Role'
    }

    def __init__(self, session_code=None, username=None, user_group_id=None, role=None):  # noqa: E501
        """AssignAdaptorUserToUserGroupModel - a model defined in Swagger"""  # noqa: E501
        self._session_code = None
        self._username = None
        self._user_group_id = None
        self._role = None
        self.discriminator = None
        if session_code is not None:
            self.session_code = session_code
        if username is not None:
            self.username = username
        if user_group_id is not None:
            self.user_group_id = user_group_id
        if role is not None:
            self.role = role

    @property
    def session_code(self):
        """Gets the session_code of this AssignAdaptorUserToUserGroupModel.  # noqa: E501

        Session code  # noqa: E501

        :return: The session_code of this AssignAdaptorUserToUserGroupModel.  # noqa: E501
        :rtype: str
        """
        return self._session_code

    @session_code.setter
    def session_code(self, session_code):
        """Sets the session_code of this AssignAdaptorUserToUserGroupModel.

        Session code  # noqa: E501

        :param session_code: The session_code of this AssignAdaptorUserToUserGroupModel.  # noqa: E501
        :type: str
        """

        self._session_code = session_code

    @property
    def username(self):
        """Gets the username of this AssignAdaptorUserToUserGroupModel.  # noqa: E501

        Username  # noqa: E501

        :return: The username of this AssignAdaptorUserToUserGroupModel.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this AssignAdaptorUserToUserGroupModel.

        Username  # noqa: E501

        :param username: The username of this AssignAdaptorUserToUserGroupModel.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def user_group_id(self):
        """Gets the user_group_id of this AssignAdaptorUserToUserGroupModel.  # noqa: E501

        UserGroupId  # noqa: E501

        :return: The user_group_id of this AssignAdaptorUserToUserGroupModel.  # noqa: E501
        :rtype: int
        """
        return self._user_group_id

    @user_group_id.setter
    def user_group_id(self, user_group_id):
        """Sets the user_group_id of this AssignAdaptorUserToUserGroupModel.

        UserGroupId  # noqa: E501

        :param user_group_id: The user_group_id of this AssignAdaptorUserToUserGroupModel.  # noqa: E501
        :type: int
        """

        self._user_group_id = user_group_id

    @property
    def role(self):
        """Gets the role of this AssignAdaptorUserToUserGroupModel.  # noqa: E501


        :return: The role of this AssignAdaptorUserToUserGroupModel.  # noqa: E501
        :rtype: AdaptorUserRoleType
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this AssignAdaptorUserToUserGroupModel.


        :param role: The role of this AssignAdaptorUserToUserGroupModel.  # noqa: E501
        :type: AdaptorUserRoleType
        """

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssignAdaptorUserToUserGroupModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssignAdaptorUserToUserGroupModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
