# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ByClusterAuthenticationCredentialExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cluster_authentication_credential': 'ClusterAuthenticationCredentialExt',
        'check_logs': 'list[CheckLogExt]'
    }

    attribute_map = {
        'cluster_authentication_credential': 'ClusterAuthenticationCredential',
        'check_logs': 'CheckLogs'
    }

    def __init__(self, cluster_authentication_credential=None, check_logs=None):  # noqa: E501
        """ByClusterAuthenticationCredentialExt - a model defined in Swagger"""  # noqa: E501
        self._cluster_authentication_credential = None
        self._check_logs = None
        self.discriminator = None
        if cluster_authentication_credential is not None:
            self.cluster_authentication_credential = cluster_authentication_credential
        if check_logs is not None:
            self.check_logs = check_logs

    @property
    def cluster_authentication_credential(self):
        """Gets the cluster_authentication_credential of this ByClusterAuthenticationCredentialExt.  # noqa: E501


        :return: The cluster_authentication_credential of this ByClusterAuthenticationCredentialExt.  # noqa: E501
        :rtype: ClusterAuthenticationCredentialExt
        """
        return self._cluster_authentication_credential

    @cluster_authentication_credential.setter
    def cluster_authentication_credential(self, cluster_authentication_credential):
        """Sets the cluster_authentication_credential of this ByClusterAuthenticationCredentialExt.


        :param cluster_authentication_credential: The cluster_authentication_credential of this ByClusterAuthenticationCredentialExt.  # noqa: E501
        :type: ClusterAuthenticationCredentialExt
        """

        self._cluster_authentication_credential = cluster_authentication_credential

    @property
    def check_logs(self):
        """Gets the check_logs of this ByClusterAuthenticationCredentialExt.  # noqa: E501

        CheckLogs  # noqa: E501

        :return: The check_logs of this ByClusterAuthenticationCredentialExt.  # noqa: E501
        :rtype: list[CheckLogExt]
        """
        return self._check_logs

    @check_logs.setter
    def check_logs(self, check_logs):
        """Sets the check_logs of this ByClusterAuthenticationCredentialExt.

        CheckLogs  # noqa: E501

        :param check_logs: The check_logs of this ByClusterAuthenticationCredentialExt.  # noqa: E501
        :type: list[CheckLogExt]
        """

        self._check_logs = check_logs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ByClusterAuthenticationCredentialExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ByClusterAuthenticationCredentialExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
