# coding: utf-8

"""
    py4heappe API

    Merged API documentation for py4heappe client  # noqa: E501

    OpenAPI spec version: v6.1.1
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CheckLogExt_(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'check_timestamp': 'datetime',
        'vault_credential_ok': 'bool',
        'cluster_connection_ok': 'bool',
        'dry_run_job_ok': 'bool',
        'error_message': 'str'
    }

    attribute_map = {
        'check_timestamp': 'CheckTimestamp',
        'vault_credential_ok': 'VaultCredentialOk',
        'cluster_connection_ok': 'ClusterConnectionOk',
        'dry_run_job_ok': 'DryRunJobOk',
        'error_message': 'ErrorMessage'
    }

    def __init__(self, check_timestamp=None, vault_credential_ok=None, cluster_connection_ok=None, dry_run_job_ok=None, error_message=None):  # noqa: E501
        """CheckLogExt_ - a model defined in Swagger"""  # noqa: E501
        self._check_timestamp = None
        self._vault_credential_ok = None
        self._cluster_connection_ok = None
        self._dry_run_job_ok = None
        self._error_message = None
        self.discriminator = None
        if check_timestamp is not None:
            self.check_timestamp = check_timestamp
        if vault_credential_ok is not None:
            self.vault_credential_ok = vault_credential_ok
        if cluster_connection_ok is not None:
            self.cluster_connection_ok = cluster_connection_ok
        if dry_run_job_ok is not None:
            self.dry_run_job_ok = dry_run_job_ok
        if error_message is not None:
            self.error_message = error_message

    @property
    def check_timestamp(self):
        """Gets the check_timestamp of this CheckLogExt_.  # noqa: E501

        CheckTimestamp  # noqa: E501

        :return: The check_timestamp of this CheckLogExt_.  # noqa: E501
        :rtype: datetime
        """
        return self._check_timestamp

    @check_timestamp.setter
    def check_timestamp(self, check_timestamp):
        """Sets the check_timestamp of this CheckLogExt_.

        CheckTimestamp  # noqa: E501

        :param check_timestamp: The check_timestamp of this CheckLogExt_.  # noqa: E501
        :type: datetime
        """

        self._check_timestamp = check_timestamp

    @property
    def vault_credential_ok(self):
        """Gets the vault_credential_ok of this CheckLogExt_.  # noqa: E501

        VaultCredentialOk  # noqa: E501

        :return: The vault_credential_ok of this CheckLogExt_.  # noqa: E501
        :rtype: bool
        """
        return self._vault_credential_ok

    @vault_credential_ok.setter
    def vault_credential_ok(self, vault_credential_ok):
        """Sets the vault_credential_ok of this CheckLogExt_.

        VaultCredentialOk  # noqa: E501

        :param vault_credential_ok: The vault_credential_ok of this CheckLogExt_.  # noqa: E501
        :type: bool
        """

        self._vault_credential_ok = vault_credential_ok

    @property
    def cluster_connection_ok(self):
        """Gets the cluster_connection_ok of this CheckLogExt_.  # noqa: E501

        ClusterConnectionOk  # noqa: E501

        :return: The cluster_connection_ok of this CheckLogExt_.  # noqa: E501
        :rtype: bool
        """
        return self._cluster_connection_ok

    @cluster_connection_ok.setter
    def cluster_connection_ok(self, cluster_connection_ok):
        """Sets the cluster_connection_ok of this CheckLogExt_.

        ClusterConnectionOk  # noqa: E501

        :param cluster_connection_ok: The cluster_connection_ok of this CheckLogExt_.  # noqa: E501
        :type: bool
        """

        self._cluster_connection_ok = cluster_connection_ok

    @property
    def dry_run_job_ok(self):
        """Gets the dry_run_job_ok of this CheckLogExt_.  # noqa: E501

        DryRunJobOk  # noqa: E501

        :return: The dry_run_job_ok of this CheckLogExt_.  # noqa: E501
        :rtype: bool
        """
        return self._dry_run_job_ok

    @dry_run_job_ok.setter
    def dry_run_job_ok(self, dry_run_job_ok):
        """Sets the dry_run_job_ok of this CheckLogExt_.

        DryRunJobOk  # noqa: E501

        :param dry_run_job_ok: The dry_run_job_ok of this CheckLogExt_.  # noqa: E501
        :type: bool
        """

        self._dry_run_job_ok = dry_run_job_ok

    @property
    def error_message(self):
        """Gets the error_message of this CheckLogExt_.  # noqa: E501

        ErrorMessage  # noqa: E501

        :return: The error_message of this CheckLogExt_.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this CheckLogExt_.

        ErrorMessage  # noqa: E501

        :param error_message: The error_message of this CheckLogExt_.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CheckLogExt_, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckLogExt_):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
