# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CloseQSchedulerSessionModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_code': 'str',
        'cluster_id': 'int',
        'project_id': 'int',
        'session_id': 'int'
    }

    attribute_map = {
        'session_code': 'SessionCode',
        'cluster_id': 'ClusterId',
        'project_id': 'ProjectId',
        'session_id': 'SessionId'
    }

    def __init__(self, session_code=None, cluster_id=None, project_id=None, session_id=None):  # noqa: E501
        """CloseQSchedulerSessionModel - a model defined in Swagger"""  # noqa: E501
        self._session_code = None
        self._cluster_id = None
        self._project_id = None
        self._session_id = None
        self.discriminator = None
        if session_code is not None:
            self.session_code = session_code
        if cluster_id is not None:
            self.cluster_id = cluster_id
        if project_id is not None:
            self.project_id = project_id
        if session_id is not None:
            self.session_id = session_id

    @property
    def session_code(self):
        """Gets the session_code of this CloseQSchedulerSessionModel.  # noqa: E501

        Session code  # noqa: E501

        :return: The session_code of this CloseQSchedulerSessionModel.  # noqa: E501
        :rtype: str
        """
        return self._session_code

    @session_code.setter
    def session_code(self, session_code):
        """Sets the session_code of this CloseQSchedulerSessionModel.

        Session code  # noqa: E501

        :param session_code: The session_code of this CloseQSchedulerSessionModel.  # noqa: E501
        :type: str
        """

        self._session_code = session_code

    @property
    def cluster_id(self):
        """Gets the cluster_id of this CloseQSchedulerSessionModel.  # noqa: E501

        Cluster ID  # noqa: E501

        :return: The cluster_id of this CloseQSchedulerSessionModel.  # noqa: E501
        :rtype: int
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this CloseQSchedulerSessionModel.

        Cluster ID  # noqa: E501

        :param cluster_id: The cluster_id of this CloseQSchedulerSessionModel.  # noqa: E501
        :type: int
        """

        self._cluster_id = cluster_id

    @property
    def project_id(self):
        """Gets the project_id of this CloseQSchedulerSessionModel.  # noqa: E501

        Project ID  # noqa: E501

        :return: The project_id of this CloseQSchedulerSessionModel.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this CloseQSchedulerSessionModel.

        Project ID  # noqa: E501

        :param project_id: The project_id of this CloseQSchedulerSessionModel.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def session_id(self):
        """Gets the session_id of this CloseQSchedulerSessionModel.  # noqa: E501

        Session ID to close  # noqa: E501

        :return: The session_id of this CloseQSchedulerSessionModel.  # noqa: E501
        :rtype: int
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this CloseQSchedulerSessionModel.

        Session ID to close  # noqa: E501

        :param session_id: The session_id of this CloseQSchedulerSessionModel.  # noqa: E501
        :type: int
        """

        self._session_id = session_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CloseQSchedulerSessionModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CloseQSchedulerSessionModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
