# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CloudEventExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'specversion': 'str',
        'type': 'str',
        'source': 'str',
        'id': 'str',
        'time': 'str',
        'datacontenttype': 'str',
        'data': 'object'
    }

    attribute_map = {
        'specversion': 'specversion',
        'type': 'type',
        'source': 'source',
        'id': 'id',
        'time': 'time',
        'datacontenttype': 'datacontenttype',
        'data': 'data'
    }

    def __init__(self, specversion=None, type=None, source=None, id=None, time=None, datacontenttype=None, data=None):  # noqa: E501
        """CloudEventExt - a model defined in Swagger"""  # noqa: E501
        self._specversion = None
        self._type = None
        self._source = None
        self._id = None
        self._time = None
        self._datacontenttype = None
        self._data = None
        self.discriminator = None
        if specversion is not None:
            self.specversion = specversion
        if type is not None:
            self.type = type
        if source is not None:
            self.source = source
        if id is not None:
            self.id = id
        if time is not None:
            self.time = time
        if datacontenttype is not None:
            self.datacontenttype = datacontenttype
        if data is not None:
            self.data = data

    @property
    def specversion(self):
        """Gets the specversion of this CloudEventExt.  # noqa: E501

        Version of the CloudEvents specification (1.0).  # noqa: E501

        :return: The specversion of this CloudEventExt.  # noqa: E501
        :rtype: str
        """
        return self._specversion

    @specversion.setter
    def specversion(self, specversion):
        """Sets the specversion of this CloudEventExt.

        Version of the CloudEvents specification (1.0).  # noqa: E501

        :param specversion: The specversion of this CloudEventExt.  # noqa: E501
        :type: str
        """

        self._specversion = specversion

    @property
    def type(self):
        """Gets the type of this CloudEventExt.  # noqa: E501

        Type of occurrence related to the event (e.g. org.heappe.job.state-changed).  # noqa: E501

        :return: The type of this CloudEventExt.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CloudEventExt.

        Type of occurrence related to the event (e.g. org.heappe.job.state-changed).  # noqa: E501

        :param type: The type of this CloudEventExt.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def source(self):
        """Gets the source of this CloudEventExt.  # noqa: E501

        Identifies the context in which an event happened.  # noqa: E501

        :return: The source of this CloudEventExt.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this CloudEventExt.

        Identifies the context in which an event happened.  # noqa: E501

        :param source: The source of this CloudEventExt.  # noqa: E501
        :type: str
        """

        self._source = source

    @property
    def id(self):
        """Gets the id of this CloudEventExt.  # noqa: E501

        Identifies the event.  # noqa: E501

        :return: The id of this CloudEventExt.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CloudEventExt.

        Identifies the event.  # noqa: E501

        :param id: The id of this CloudEventExt.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def time(self):
        """Gets the time of this CloudEventExt.  # noqa: E501

        Timestamp of when the event occurred.  # noqa: E501

        :return: The time of this CloudEventExt.  # noqa: E501
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this CloudEventExt.

        Timestamp of when the event occurred.  # noqa: E501

        :param time: The time of this CloudEventExt.  # noqa: E501
        :type: str
        """

        self._time = time

    @property
    def datacontenttype(self):
        """Gets the datacontenttype of this CloudEventExt.  # noqa: E501

        Content type of the data value.  # noqa: E501

        :return: The datacontenttype of this CloudEventExt.  # noqa: E501
        :rtype: str
        """
        return self._datacontenttype

    @datacontenttype.setter
    def datacontenttype(self, datacontenttype):
        """Sets the datacontenttype of this CloudEventExt.

        Content type of the data value.  # noqa: E501

        :param datacontenttype: The datacontenttype of this CloudEventExt.  # noqa: E501
        :type: str
        """

        self._datacontenttype = datacontenttype

    @property
    def data(self):
        """Gets the data of this CloudEventExt.  # noqa: E501

        The event payload.  # noqa: E501

        :return: The data of this CloudEventExt.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CloudEventExt.

        The event payload.  # noqa: E501

        :param data: The data of this CloudEventExt.  # noqa: E501
        :type: object
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CloudEventExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CloudEventExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
