# coding: utf-8

"""
    py4heappe API

    Merged API documentation for py4heappe client  # noqa: E501

    OpenAPI spec version: v6.2.0
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClusterConnectionCountsExt_(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ok_count': 'int',
        'fail_count': 'int'
    }

    attribute_map = {
        'ok_count': 'OkCount',
        'fail_count': 'FailCount'
    }

    def __init__(self, ok_count=None, fail_count=None):  # noqa: E501
        """ClusterConnectionCountsExt_ - a model defined in Swagger"""  # noqa: E501
        self._ok_count = None
        self._fail_count = None
        self.discriminator = None
        if ok_count is not None:
            self.ok_count = ok_count
        if fail_count is not None:
            self.fail_count = fail_count

    @property
    def ok_count(self):
        """Gets the ok_count of this ClusterConnectionCountsExt_.  # noqa: E501

        OkCount  # noqa: E501

        :return: The ok_count of this ClusterConnectionCountsExt_.  # noqa: E501
        :rtype: int
        """
        return self._ok_count

    @ok_count.setter
    def ok_count(self, ok_count):
        """Sets the ok_count of this ClusterConnectionCountsExt_.

        OkCount  # noqa: E501

        :param ok_count: The ok_count of this ClusterConnectionCountsExt_.  # noqa: E501
        :type: int
        """

        self._ok_count = ok_count

    @property
    def fail_count(self):
        """Gets the fail_count of this ClusterConnectionCountsExt_.  # noqa: E501

        FailCount  # noqa: E501

        :return: The fail_count of this ClusterConnectionCountsExt_.  # noqa: E501
        :rtype: int
        """
        return self._fail_count

    @fail_count.setter
    def fail_count(self, fail_count):
        """Sets the fail_count of this ClusterConnectionCountsExt_.

        FailCount  # noqa: E501

        :param fail_count: The fail_count of this ClusterConnectionCountsExt_.  # noqa: E501
        :type: int
        """

        self._fail_count = fail_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClusterConnectionCountsExt_, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClusterConnectionCountsExt_):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
