# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClusterProjectStoragePathExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cluster_id': 'int',
        'cluster_name': 'str',
        'scratch_storage_path': 'str',
        'project_storage_path': 'str'
    }

    attribute_map = {
        'cluster_id': 'ClusterId',
        'cluster_name': 'ClusterName',
        'scratch_storage_path': 'ScratchStoragePath',
        'project_storage_path': 'ProjectStoragePath'
    }

    def __init__(self, cluster_id=None, cluster_name=None, scratch_storage_path=None, project_storage_path=None):  # noqa: E501
        """ClusterProjectStoragePathExt - a model defined in Swagger"""  # noqa: E501
        self._cluster_id = None
        self._cluster_name = None
        self._scratch_storage_path = None
        self._project_storage_path = None
        self.discriminator = None
        if cluster_id is not None:
            self.cluster_id = cluster_id
        if cluster_name is not None:
            self.cluster_name = cluster_name
        if scratch_storage_path is not None:
            self.scratch_storage_path = scratch_storage_path
        if project_storage_path is not None:
            self.project_storage_path = project_storage_path

    @property
    def cluster_id(self):
        """Gets the cluster_id of this ClusterProjectStoragePathExt.  # noqa: E501

        Cluster Id  # noqa: E501

        :return: The cluster_id of this ClusterProjectStoragePathExt.  # noqa: E501
        :rtype: int
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this ClusterProjectStoragePathExt.

        Cluster Id  # noqa: E501

        :param cluster_id: The cluster_id of this ClusterProjectStoragePathExt.  # noqa: E501
        :type: int
        """

        self._cluster_id = cluster_id

    @property
    def cluster_name(self):
        """Gets the cluster_name of this ClusterProjectStoragePathExt.  # noqa: E501

        Cluster Name  # noqa: E501

        :return: The cluster_name of this ClusterProjectStoragePathExt.  # noqa: E501
        :rtype: str
        """
        return self._cluster_name

    @cluster_name.setter
    def cluster_name(self, cluster_name):
        """Sets the cluster_name of this ClusterProjectStoragePathExt.

        Cluster Name  # noqa: E501

        :param cluster_name: The cluster_name of this ClusterProjectStoragePathExt.  # noqa: E501
        :type: str
        """

        self._cluster_name = cluster_name

    @property
    def scratch_storage_path(self):
        """Gets the scratch_storage_path of this ClusterProjectStoragePathExt.  # noqa: E501

        Scratch storage path  # noqa: E501

        :return: The scratch_storage_path of this ClusterProjectStoragePathExt.  # noqa: E501
        :rtype: str
        """
        return self._scratch_storage_path

    @scratch_storage_path.setter
    def scratch_storage_path(self, scratch_storage_path):
        """Sets the scratch_storage_path of this ClusterProjectStoragePathExt.

        Scratch storage path  # noqa: E501

        :param scratch_storage_path: The scratch_storage_path of this ClusterProjectStoragePathExt.  # noqa: E501
        :type: str
        """

        self._scratch_storage_path = scratch_storage_path

    @property
    def project_storage_path(self):
        """Gets the project_storage_path of this ClusterProjectStoragePathExt.  # noqa: E501

        Project storage path  # noqa: E501

        :return: The project_storage_path of this ClusterProjectStoragePathExt.  # noqa: E501
        :rtype: str
        """
        return self._project_storage_path

    @project_storage_path.setter
    def project_storage_path(self, project_storage_path):
        """Sets the project_storage_path of this ClusterProjectStoragePathExt.

        Project storage path  # noqa: E501

        :param project_storage_path: The project_storage_path of this ClusterProjectStoragePathExt.  # noqa: E501
        :type: str
        """

        self._project_storage_path = project_storage_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClusterProjectStoragePathExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClusterProjectStoragePathExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
