# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CredentialResponseExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'username': 'str',
        'auth_type': 'ClusterAuthenticationCredentialsAuthType',
        'is_generated': 'bool',
        'public_key_fingerprint': 'str',
        'public_key_ext': 'str',
        'adaptor_user_id': 'int'
    }

    attribute_map = {
        'id': 'Id',
        'username': 'Username',
        'auth_type': 'AuthType',
        'is_generated': 'IsGenerated',
        'public_key_fingerprint': 'PublicKeyFingerprint',
        'public_key_ext': 'PublicKeyExt',
        'adaptor_user_id': 'AdaptorUserId'
    }

    def __init__(self, id=None, username=None, auth_type=None, is_generated=None, public_key_fingerprint=None, public_key_ext=None, adaptor_user_id=None):  # noqa: E501
        """CredentialResponseExt - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._username = None
        self._auth_type = None
        self._is_generated = None
        self._public_key_fingerprint = None
        self._public_key_ext = None
        self._adaptor_user_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if username is not None:
            self.username = username
        if auth_type is not None:
            self.auth_type = auth_type
        if is_generated is not None:
            self.is_generated = is_generated
        if public_key_fingerprint is not None:
            self.public_key_fingerprint = public_key_fingerprint
        if public_key_ext is not None:
            self.public_key_ext = public_key_ext
        if adaptor_user_id is not None:
            self.adaptor_user_id = adaptor_user_id

    @property
    def id(self):
        """Gets the id of this CredentialResponseExt.  # noqa: E501

        Id  # noqa: E501

        :return: The id of this CredentialResponseExt.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CredentialResponseExt.

        Id  # noqa: E501

        :param id: The id of this CredentialResponseExt.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def username(self):
        """Gets the username of this CredentialResponseExt.  # noqa: E501

        Username  # noqa: E501

        :return: The username of this CredentialResponseExt.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this CredentialResponseExt.

        Username  # noqa: E501

        :param username: The username of this CredentialResponseExt.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def auth_type(self):
        """Gets the auth_type of this CredentialResponseExt.  # noqa: E501


        :return: The auth_type of this CredentialResponseExt.  # noqa: E501
        :rtype: ClusterAuthenticationCredentialsAuthType
        """
        return self._auth_type

    @auth_type.setter
    def auth_type(self, auth_type):
        """Sets the auth_type of this CredentialResponseExt.


        :param auth_type: The auth_type of this CredentialResponseExt.  # noqa: E501
        :type: ClusterAuthenticationCredentialsAuthType
        """

        self._auth_type = auth_type

    @property
    def is_generated(self):
        """Gets the is_generated of this CredentialResponseExt.  # noqa: E501

        Is generated  # noqa: E501

        :return: The is_generated of this CredentialResponseExt.  # noqa: E501
        :rtype: bool
        """
        return self._is_generated

    @is_generated.setter
    def is_generated(self, is_generated):
        """Sets the is_generated of this CredentialResponseExt.

        Is generated  # noqa: E501

        :param is_generated: The is_generated of this CredentialResponseExt.  # noqa: E501
        :type: bool
        """

        self._is_generated = is_generated

    @property
    def public_key_fingerprint(self):
        """Gets the public_key_fingerprint of this CredentialResponseExt.  # noqa: E501

        Public key fingerprint  # noqa: E501

        :return: The public_key_fingerprint of this CredentialResponseExt.  # noqa: E501
        :rtype: str
        """
        return self._public_key_fingerprint

    @public_key_fingerprint.setter
    def public_key_fingerprint(self, public_key_fingerprint):
        """Sets the public_key_fingerprint of this CredentialResponseExt.

        Public key fingerprint  # noqa: E501

        :param public_key_fingerprint: The public_key_fingerprint of this CredentialResponseExt.  # noqa: E501
        :type: str
        """

        self._public_key_fingerprint = public_key_fingerprint

    @property
    def public_key_ext(self):
        """Gets the public_key_ext of this CredentialResponseExt.  # noqa: E501

        Public key ext  # noqa: E501

        :return: The public_key_ext of this CredentialResponseExt.  # noqa: E501
        :rtype: str
        """
        return self._public_key_ext

    @public_key_ext.setter
    def public_key_ext(self, public_key_ext):
        """Sets the public_key_ext of this CredentialResponseExt.

        Public key ext  # noqa: E501

        :param public_key_ext: The public_key_ext of this CredentialResponseExt.  # noqa: E501
        :type: str
        """

        self._public_key_ext = public_key_ext

    @property
    def adaptor_user_id(self):
        """Gets the adaptor_user_id of this CredentialResponseExt.  # noqa: E501

        Adaptor user id  # noqa: E501

        :return: The adaptor_user_id of this CredentialResponseExt.  # noqa: E501
        :rtype: int
        """
        return self._adaptor_user_id

    @adaptor_user_id.setter
    def adaptor_user_id(self, adaptor_user_id):
        """Sets the adaptor_user_id of this CredentialResponseExt.

        Adaptor user id  # noqa: E501

        :param adaptor_user_id: The adaptor_user_id of this CredentialResponseExt.  # noqa: E501
        :type: int
        """

        self._adaptor_user_id = adaptor_user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CredentialResponseExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CredentialResponseExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
