# coding: utf-8

"""
    py4heappe API

    Merged API documentation for py4heappe client  # noqa: E501

    OpenAPI spec version: v6.1.1
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DetailExt_(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'check_timestamp': 'datetime',
        'cluster_authentication_credential': 'ClusterAuthenticationCredentialExt_',
        'vault_credential': 'VaultCredentialCountsExt_',
        'cluster_connection': 'ClusterConnectionCountsExt_',
        'dry_run_job': 'DryRunJobCountsExt_',
        'errors': 'list[CheckLogExt_]'
    }

    attribute_map = {
        'check_timestamp': 'CheckTimestamp',
        'cluster_authentication_credential': 'ClusterAuthenticationCredential',
        'vault_credential': 'VaultCredential',
        'cluster_connection': 'ClusterConnection',
        'dry_run_job': 'DryRunJob',
        'errors': 'Errors'
    }

    def __init__(self, check_timestamp=None, cluster_authentication_credential=None, vault_credential=None, cluster_connection=None, dry_run_job=None, errors=None):  # noqa: E501
        """DetailExt_ - a model defined in Swagger"""  # noqa: E501
        self._check_timestamp = None
        self._cluster_authentication_credential = None
        self._vault_credential = None
        self._cluster_connection = None
        self._dry_run_job = None
        self._errors = None
        self.discriminator = None
        if check_timestamp is not None:
            self.check_timestamp = check_timestamp
        if cluster_authentication_credential is not None:
            self.cluster_authentication_credential = cluster_authentication_credential
        if vault_credential is not None:
            self.vault_credential = vault_credential
        if cluster_connection is not None:
            self.cluster_connection = cluster_connection
        if dry_run_job is not None:
            self.dry_run_job = dry_run_job
        if errors is not None:
            self.errors = errors

    @property
    def check_timestamp(self):
        """Gets the check_timestamp of this DetailExt_.  # noqa: E501

        CheckTimestamp  # noqa: E501

        :return: The check_timestamp of this DetailExt_.  # noqa: E501
        :rtype: datetime
        """
        return self._check_timestamp

    @check_timestamp.setter
    def check_timestamp(self, check_timestamp):
        """Sets the check_timestamp of this DetailExt_.

        CheckTimestamp  # noqa: E501

        :param check_timestamp: The check_timestamp of this DetailExt_.  # noqa: E501
        :type: datetime
        """

        self._check_timestamp = check_timestamp

    @property
    def cluster_authentication_credential(self):
        """Gets the cluster_authentication_credential of this DetailExt_.  # noqa: E501


        :return: The cluster_authentication_credential of this DetailExt_.  # noqa: E501
        :rtype: ClusterAuthenticationCredentialExt_
        """
        return self._cluster_authentication_credential

    @cluster_authentication_credential.setter
    def cluster_authentication_credential(self, cluster_authentication_credential):
        """Sets the cluster_authentication_credential of this DetailExt_.


        :param cluster_authentication_credential: The cluster_authentication_credential of this DetailExt_.  # noqa: E501
        :type: ClusterAuthenticationCredentialExt_
        """

        self._cluster_authentication_credential = cluster_authentication_credential

    @property
    def vault_credential(self):
        """Gets the vault_credential of this DetailExt_.  # noqa: E501


        :return: The vault_credential of this DetailExt_.  # noqa: E501
        :rtype: VaultCredentialCountsExt_
        """
        return self._vault_credential

    @vault_credential.setter
    def vault_credential(self, vault_credential):
        """Sets the vault_credential of this DetailExt_.


        :param vault_credential: The vault_credential of this DetailExt_.  # noqa: E501
        :type: VaultCredentialCountsExt_
        """

        self._vault_credential = vault_credential

    @property
    def cluster_connection(self):
        """Gets the cluster_connection of this DetailExt_.  # noqa: E501


        :return: The cluster_connection of this DetailExt_.  # noqa: E501
        :rtype: ClusterConnectionCountsExt_
        """
        return self._cluster_connection

    @cluster_connection.setter
    def cluster_connection(self, cluster_connection):
        """Sets the cluster_connection of this DetailExt_.


        :param cluster_connection: The cluster_connection of this DetailExt_.  # noqa: E501
        :type: ClusterConnectionCountsExt_
        """

        self._cluster_connection = cluster_connection

    @property
    def dry_run_job(self):
        """Gets the dry_run_job of this DetailExt_.  # noqa: E501


        :return: The dry_run_job of this DetailExt_.  # noqa: E501
        :rtype: DryRunJobCountsExt_
        """
        return self._dry_run_job

    @dry_run_job.setter
    def dry_run_job(self, dry_run_job):
        """Sets the dry_run_job of this DetailExt_.


        :param dry_run_job: The dry_run_job of this DetailExt_.  # noqa: E501
        :type: DryRunJobCountsExt_
        """

        self._dry_run_job = dry_run_job

    @property
    def errors(self):
        """Gets the errors of this DetailExt_.  # noqa: E501

        Errors  # noqa: E501

        :return: The errors of this DetailExt_.  # noqa: E501
        :rtype: list[CheckLogExt_]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this DetailExt_.

        Errors  # noqa: E501

        :param errors: The errors of this DetailExt_.  # noqa: E501
        :type: list[CheckLogExt_]
        """

        self._errors = errors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DetailExt_, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DetailExt_):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
