# coding: utf-8

"""
    py4heappe API

    Merged API documentation for py4heappe client  # noqa: E501

    OpenAPI spec version: v6.2.0
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DryRunJobModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_code': 'str',
        'project_id': 'int',
        'cluster_node_type_id': 'int',
        'nodes': 'int',
        'tasks_per_node': 'int',
        'wall_time_in_minutes': 'int'
    }

    attribute_map = {
        'session_code': 'SessionCode',
        'project_id': 'ProjectId',
        'cluster_node_type_id': 'ClusterNodeTypeId',
        'nodes': 'Nodes',
        'tasks_per_node': 'TasksPerNode',
        'wall_time_in_minutes': 'WallTimeInMinutes'
    }

    def __init__(self, session_code=None, project_id=None, cluster_node_type_id=None, nodes=None, tasks_per_node=None, wall_time_in_minutes=None):  # noqa: E501
        """DryRunJobModel - a model defined in Swagger"""  # noqa: E501
        self._session_code = None
        self._project_id = None
        self._cluster_node_type_id = None
        self._nodes = None
        self._tasks_per_node = None
        self._wall_time_in_minutes = None
        self.discriminator = None
        if session_code is not None:
            self.session_code = session_code
        self.project_id = project_id
        self.cluster_node_type_id = cluster_node_type_id
        self.nodes = nodes
        self.tasks_per_node = tasks_per_node
        self.wall_time_in_minutes = wall_time_in_minutes

    @property
    def session_code(self):
        """Gets the session_code of this DryRunJobModel.  # noqa: E501

        Session code  # noqa: E501

        :return: The session_code of this DryRunJobModel.  # noqa: E501
        :rtype: str
        """
        return self._session_code

    @session_code.setter
    def session_code(self, session_code):
        """Sets the session_code of this DryRunJobModel.

        Session code  # noqa: E501

        :param session_code: The session_code of this DryRunJobModel.  # noqa: E501
        :type: str
        """

        self._session_code = session_code

    @property
    def project_id(self):
        """Gets the project_id of this DryRunJobModel.  # noqa: E501

        ProjectId  # noqa: E501

        :return: The project_id of this DryRunJobModel.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this DryRunJobModel.

        ProjectId  # noqa: E501

        :param project_id: The project_id of this DryRunJobModel.  # noqa: E501
        :type: int
        """
        if project_id is None:
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def cluster_node_type_id(self):
        """Gets the cluster_node_type_id of this DryRunJobModel.  # noqa: E501

        Cluster Node Type Id  # noqa: E501

        :return: The cluster_node_type_id of this DryRunJobModel.  # noqa: E501
        :rtype: int
        """
        return self._cluster_node_type_id

    @cluster_node_type_id.setter
    def cluster_node_type_id(self, cluster_node_type_id):
        """Sets the cluster_node_type_id of this DryRunJobModel.

        Cluster Node Type Id  # noqa: E501

        :param cluster_node_type_id: The cluster_node_type_id of this DryRunJobModel.  # noqa: E501
        :type: int
        """
        if cluster_node_type_id is None:
            raise ValueError("Invalid value for `cluster_node_type_id`, must not be `None`")  # noqa: E501

        self._cluster_node_type_id = cluster_node_type_id

    @property
    def nodes(self):
        """Gets the nodes of this DryRunJobModel.  # noqa: E501

        Number of nodes  # noqa: E501

        :return: The nodes of this DryRunJobModel.  # noqa: E501
        :rtype: int
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes):
        """Sets the nodes of this DryRunJobModel.

        Number of nodes  # noqa: E501

        :param nodes: The nodes of this DryRunJobModel.  # noqa: E501
        :type: int
        """
        if nodes is None:
            raise ValueError("Invalid value for `nodes`, must not be `None`")  # noqa: E501

        self._nodes = nodes

    @property
    def tasks_per_node(self):
        """Gets the tasks_per_node of this DryRunJobModel.  # noqa: E501

        Number of tasks per node  # noqa: E501

        :return: The tasks_per_node of this DryRunJobModel.  # noqa: E501
        :rtype: int
        """
        return self._tasks_per_node

    @tasks_per_node.setter
    def tasks_per_node(self, tasks_per_node):
        """Sets the tasks_per_node of this DryRunJobModel.

        Number of tasks per node  # noqa: E501

        :param tasks_per_node: The tasks_per_node of this DryRunJobModel.  # noqa: E501
        :type: int
        """
        if tasks_per_node is None:
            raise ValueError("Invalid value for `tasks_per_node`, must not be `None`")  # noqa: E501

        self._tasks_per_node = tasks_per_node

    @property
    def wall_time_in_minutes(self):
        """Gets the wall_time_in_minutes of this DryRunJobModel.  # noqa: E501

        Wall time in minutes  # noqa: E501

        :return: The wall_time_in_minutes of this DryRunJobModel.  # noqa: E501
        :rtype: int
        """
        return self._wall_time_in_minutes

    @wall_time_in_minutes.setter
    def wall_time_in_minutes(self, wall_time_in_minutes):
        """Sets the wall_time_in_minutes of this DryRunJobModel.

        Wall time in minutes  # noqa: E501

        :param wall_time_in_minutes: The wall_time_in_minutes of this DryRunJobModel.  # noqa: E501
        :type: int
        """
        if wall_time_in_minutes is None:
            raise ValueError("Invalid value for `wall_time_in_minutes`, must not be `None`")  # noqa: E501

        self._wall_time_in_minutes = wall_time_in_minutes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DryRunJobModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DryRunJobModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
