# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DryRunJobInfoExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'job_id': 'int',
        'start_time': 'datetime',
        'processors': 'int',
        'node': 'str',
        'partition': 'str',
        'message': 'str'
    }

    attribute_map = {
        'job_id': 'JobId',
        'start_time': 'StartTime',
        'processors': 'Processors',
        'node': 'Node',
        'partition': 'Partition',
        'message': 'Message'
    }

    def __init__(self, job_id=None, start_time=None, processors=None, node=None, partition=None, message=None):  # noqa: E501
        """DryRunJobInfoExt - a model defined in Swagger"""  # noqa: E501
        self._job_id = None
        self._start_time = None
        self._processors = None
        self._node = None
        self._partition = None
        self._message = None
        self.discriminator = None
        if job_id is not None:
            self.job_id = job_id
        if start_time is not None:
            self.start_time = start_time
        if processors is not None:
            self.processors = processors
        if node is not None:
            self.node = node
        if partition is not None:
            self.partition = partition
        if message is not None:
            self.message = message

    @property
    def job_id(self):
        """Gets the job_id of this DryRunJobInfoExt.  # noqa: E501


        :return: The job_id of this DryRunJobInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this DryRunJobInfoExt.


        :param job_id: The job_id of this DryRunJobInfoExt.  # noqa: E501
        :type: int
        """

        self._job_id = job_id

    @property
    def start_time(self):
        """Gets the start_time of this DryRunJobInfoExt.  # noqa: E501


        :return: The start_time of this DryRunJobInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this DryRunJobInfoExt.


        :param start_time: The start_time of this DryRunJobInfoExt.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def processors(self):
        """Gets the processors of this DryRunJobInfoExt.  # noqa: E501


        :return: The processors of this DryRunJobInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._processors

    @processors.setter
    def processors(self, processors):
        """Sets the processors of this DryRunJobInfoExt.


        :param processors: The processors of this DryRunJobInfoExt.  # noqa: E501
        :type: int
        """

        self._processors = processors

    @property
    def node(self):
        """Gets the node of this DryRunJobInfoExt.  # noqa: E501


        :return: The node of this DryRunJobInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._node

    @node.setter
    def node(self, node):
        """Sets the node of this DryRunJobInfoExt.


        :param node: The node of this DryRunJobInfoExt.  # noqa: E501
        :type: str
        """

        self._node = node

    @property
    def partition(self):
        """Gets the partition of this DryRunJobInfoExt.  # noqa: E501


        :return: The partition of this DryRunJobInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._partition

    @partition.setter
    def partition(self, partition):
        """Sets the partition of this DryRunJobInfoExt.


        :param partition: The partition of this DryRunJobInfoExt.  # noqa: E501
        :type: str
        """

        self._partition = partition

    @property
    def message(self):
        """Gets the message of this DryRunJobInfoExt.  # noqa: E501


        :return: The message of this DryRunJobInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this DryRunJobInfoExt.


        :param message: The message of this DryRunJobInfoExt.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DryRunJobInfoExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DryRunJobInfoExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
