# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExternalServiceStatisticsExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service_name': 'str',
        'service_type': 'str',
        'command_or_path': 'str',
        'availability_percentage': 'float',
        'average_response_time_ms': 'int',
        'min_response_time_ms': 'int',
        'max_response_time_ms': 'int',
        'p95_response_time_ms': 'int',
        'total_checks': 'int',
        'failed_checks': 'int'
    }

    attribute_map = {
        'service_name': 'ServiceName',
        'service_type': 'ServiceType',
        'command_or_path': 'CommandOrPath',
        'availability_percentage': 'AvailabilityPercentage',
        'average_response_time_ms': 'AverageResponseTimeMs',
        'min_response_time_ms': 'MinResponseTimeMs',
        'max_response_time_ms': 'MaxResponseTimeMs',
        'p95_response_time_ms': 'P95ResponseTimeMs',
        'total_checks': 'TotalChecks',
        'failed_checks': 'FailedChecks'
    }

    def __init__(self, service_name=None, service_type=None, command_or_path=None, availability_percentage=None, average_response_time_ms=None, min_response_time_ms=None, max_response_time_ms=None, p95_response_time_ms=None, total_checks=None, failed_checks=None):  # noqa: E501
        """ExternalServiceStatisticsExt - a model defined in Swagger"""  # noqa: E501
        self._service_name = None
        self._service_type = None
        self._command_or_path = None
        self._availability_percentage = None
        self._average_response_time_ms = None
        self._min_response_time_ms = None
        self._max_response_time_ms = None
        self._p95_response_time_ms = None
        self._total_checks = None
        self._failed_checks = None
        self.discriminator = None
        if service_name is not None:
            self.service_name = service_name
        if service_type is not None:
            self.service_type = service_type
        if command_or_path is not None:
            self.command_or_path = command_or_path
        if availability_percentage is not None:
            self.availability_percentage = availability_percentage
        if average_response_time_ms is not None:
            self.average_response_time_ms = average_response_time_ms
        if min_response_time_ms is not None:
            self.min_response_time_ms = min_response_time_ms
        if max_response_time_ms is not None:
            self.max_response_time_ms = max_response_time_ms
        if p95_response_time_ms is not None:
            self.p95_response_time_ms = p95_response_time_ms
        if total_checks is not None:
            self.total_checks = total_checks
        if failed_checks is not None:
            self.failed_checks = failed_checks

    @property
    def service_name(self):
        """Gets the service_name of this ExternalServiceStatisticsExt.  # noqa: E501


        :return: The service_name of this ExternalServiceStatisticsExt.  # noqa: E501
        :rtype: str
        """
        return self._service_name

    @service_name.setter
    def service_name(self, service_name):
        """Sets the service_name of this ExternalServiceStatisticsExt.


        :param service_name: The service_name of this ExternalServiceStatisticsExt.  # noqa: E501
        :type: str
        """

        self._service_name = service_name

    @property
    def service_type(self):
        """Gets the service_type of this ExternalServiceStatisticsExt.  # noqa: E501


        :return: The service_type of this ExternalServiceStatisticsExt.  # noqa: E501
        :rtype: str
        """
        return self._service_type

    @service_type.setter
    def service_type(self, service_type):
        """Sets the service_type of this ExternalServiceStatisticsExt.


        :param service_type: The service_type of this ExternalServiceStatisticsExt.  # noqa: E501
        :type: str
        """

        self._service_type = service_type

    @property
    def command_or_path(self):
        """Gets the command_or_path of this ExternalServiceStatisticsExt.  # noqa: E501


        :return: The command_or_path of this ExternalServiceStatisticsExt.  # noqa: E501
        :rtype: str
        """
        return self._command_or_path

    @command_or_path.setter
    def command_or_path(self, command_or_path):
        """Sets the command_or_path of this ExternalServiceStatisticsExt.


        :param command_or_path: The command_or_path of this ExternalServiceStatisticsExt.  # noqa: E501
        :type: str
        """

        self._command_or_path = command_or_path

    @property
    def availability_percentage(self):
        """Gets the availability_percentage of this ExternalServiceStatisticsExt.  # noqa: E501


        :return: The availability_percentage of this ExternalServiceStatisticsExt.  # noqa: E501
        :rtype: float
        """
        return self._availability_percentage

    @availability_percentage.setter
    def availability_percentage(self, availability_percentage):
        """Sets the availability_percentage of this ExternalServiceStatisticsExt.


        :param availability_percentage: The availability_percentage of this ExternalServiceStatisticsExt.  # noqa: E501
        :type: float
        """

        self._availability_percentage = availability_percentage

    @property
    def average_response_time_ms(self):
        """Gets the average_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501


        :return: The average_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501
        :rtype: int
        """
        return self._average_response_time_ms

    @average_response_time_ms.setter
    def average_response_time_ms(self, average_response_time_ms):
        """Sets the average_response_time_ms of this ExternalServiceStatisticsExt.


        :param average_response_time_ms: The average_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501
        :type: int
        """

        self._average_response_time_ms = average_response_time_ms

    @property
    def min_response_time_ms(self):
        """Gets the min_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501


        :return: The min_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501
        :rtype: int
        """
        return self._min_response_time_ms

    @min_response_time_ms.setter
    def min_response_time_ms(self, min_response_time_ms):
        """Sets the min_response_time_ms of this ExternalServiceStatisticsExt.


        :param min_response_time_ms: The min_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501
        :type: int
        """

        self._min_response_time_ms = min_response_time_ms

    @property
    def max_response_time_ms(self):
        """Gets the max_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501


        :return: The max_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501
        :rtype: int
        """
        return self._max_response_time_ms

    @max_response_time_ms.setter
    def max_response_time_ms(self, max_response_time_ms):
        """Sets the max_response_time_ms of this ExternalServiceStatisticsExt.


        :param max_response_time_ms: The max_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501
        :type: int
        """

        self._max_response_time_ms = max_response_time_ms

    @property
    def p95_response_time_ms(self):
        """Gets the p95_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501


        :return: The p95_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501
        :rtype: int
        """
        return self._p95_response_time_ms

    @p95_response_time_ms.setter
    def p95_response_time_ms(self, p95_response_time_ms):
        """Sets the p95_response_time_ms of this ExternalServiceStatisticsExt.


        :param p95_response_time_ms: The p95_response_time_ms of this ExternalServiceStatisticsExt.  # noqa: E501
        :type: int
        """

        self._p95_response_time_ms = p95_response_time_ms

    @property
    def total_checks(self):
        """Gets the total_checks of this ExternalServiceStatisticsExt.  # noqa: E501


        :return: The total_checks of this ExternalServiceStatisticsExt.  # noqa: E501
        :rtype: int
        """
        return self._total_checks

    @total_checks.setter
    def total_checks(self, total_checks):
        """Sets the total_checks of this ExternalServiceStatisticsExt.


        :param total_checks: The total_checks of this ExternalServiceStatisticsExt.  # noqa: E501
        :type: int
        """

        self._total_checks = total_checks

    @property
    def failed_checks(self):
        """Gets the failed_checks of this ExternalServiceStatisticsExt.  # noqa: E501


        :return: The failed_checks of this ExternalServiceStatisticsExt.  # noqa: E501
        :rtype: int
        """
        return self._failed_checks

    @failed_checks.setter
    def failed_checks(self, failed_checks):
        """Sets the failed_checks of this ExternalServiceStatisticsExt.


        :param failed_checks: The failed_checks of this ExternalServiceStatisticsExt.  # noqa: E501
        :type: int
        """

        self._failed_checks = failed_checks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalServiceStatisticsExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalServiceStatisticsExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
