# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExternalServiceLiveStatusExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service_name': 'str',
        'type': 'str',
        'protocol': 'str',
        'endpoint_or_host': 'str',
        'port': 'int',
        'is_available': 'bool',
        'response_time_ms': 'int',
        'error_message': 'str',
        'last_check': 'datetime'
    }

    attribute_map = {
        'service_name': 'ServiceName',
        'type': 'Type',
        'protocol': 'Protocol',
        'endpoint_or_host': 'EndpointOrHost',
        'port': 'Port',
        'is_available': 'IsAvailable',
        'response_time_ms': 'ResponseTimeMs',
        'error_message': 'ErrorMessage',
        'last_check': 'LastCheck'
    }

    def __init__(self, service_name=None, type=None, protocol=None, endpoint_or_host=None, port=None, is_available=None, response_time_ms=None, error_message=None, last_check=None):  # noqa: E501
        """ExternalServiceLiveStatusExt - a model defined in Swagger"""  # noqa: E501
        self._service_name = None
        self._type = None
        self._protocol = None
        self._endpoint_or_host = None
        self._port = None
        self._is_available = None
        self._response_time_ms = None
        self._error_message = None
        self._last_check = None
        self.discriminator = None
        if service_name is not None:
            self.service_name = service_name
        if type is not None:
            self.type = type
        if protocol is not None:
            self.protocol = protocol
        if endpoint_or_host is not None:
            self.endpoint_or_host = endpoint_or_host
        if port is not None:
            self.port = port
        if is_available is not None:
            self.is_available = is_available
        if response_time_ms is not None:
            self.response_time_ms = response_time_ms
        if error_message is not None:
            self.error_message = error_message
        if last_check is not None:
            self.last_check = last_check

    @property
    def service_name(self):
        """Gets the service_name of this ExternalServiceLiveStatusExt.  # noqa: E501


        :return: The service_name of this ExternalServiceLiveStatusExt.  # noqa: E501
        :rtype: str
        """
        return self._service_name

    @service_name.setter
    def service_name(self, service_name):
        """Sets the service_name of this ExternalServiceLiveStatusExt.


        :param service_name: The service_name of this ExternalServiceLiveStatusExt.  # noqa: E501
        :type: str
        """

        self._service_name = service_name

    @property
    def type(self):
        """Gets the type of this ExternalServiceLiveStatusExt.  # noqa: E501


        :return: The type of this ExternalServiceLiveStatusExt.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ExternalServiceLiveStatusExt.


        :param type: The type of this ExternalServiceLiveStatusExt.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def protocol(self):
        """Gets the protocol of this ExternalServiceLiveStatusExt.  # noqa: E501


        :return: The protocol of this ExternalServiceLiveStatusExt.  # noqa: E501
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """Sets the protocol of this ExternalServiceLiveStatusExt.


        :param protocol: The protocol of this ExternalServiceLiveStatusExt.  # noqa: E501
        :type: str
        """

        self._protocol = protocol

    @property
    def endpoint_or_host(self):
        """Gets the endpoint_or_host of this ExternalServiceLiveStatusExt.  # noqa: E501


        :return: The endpoint_or_host of this ExternalServiceLiveStatusExt.  # noqa: E501
        :rtype: str
        """
        return self._endpoint_or_host

    @endpoint_or_host.setter
    def endpoint_or_host(self, endpoint_or_host):
        """Sets the endpoint_or_host of this ExternalServiceLiveStatusExt.


        :param endpoint_or_host: The endpoint_or_host of this ExternalServiceLiveStatusExt.  # noqa: E501
        :type: str
        """

        self._endpoint_or_host = endpoint_or_host

    @property
    def port(self):
        """Gets the port of this ExternalServiceLiveStatusExt.  # noqa: E501


        :return: The port of this ExternalServiceLiveStatusExt.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this ExternalServiceLiveStatusExt.


        :param port: The port of this ExternalServiceLiveStatusExt.  # noqa: E501
        :type: int
        """

        self._port = port

    @property
    def is_available(self):
        """Gets the is_available of this ExternalServiceLiveStatusExt.  # noqa: E501


        :return: The is_available of this ExternalServiceLiveStatusExt.  # noqa: E501
        :rtype: bool
        """
        return self._is_available

    @is_available.setter
    def is_available(self, is_available):
        """Sets the is_available of this ExternalServiceLiveStatusExt.


        :param is_available: The is_available of this ExternalServiceLiveStatusExt.  # noqa: E501
        :type: bool
        """

        self._is_available = is_available

    @property
    def response_time_ms(self):
        """Gets the response_time_ms of this ExternalServiceLiveStatusExt.  # noqa: E501


        :return: The response_time_ms of this ExternalServiceLiveStatusExt.  # noqa: E501
        :rtype: int
        """
        return self._response_time_ms

    @response_time_ms.setter
    def response_time_ms(self, response_time_ms):
        """Sets the response_time_ms of this ExternalServiceLiveStatusExt.


        :param response_time_ms: The response_time_ms of this ExternalServiceLiveStatusExt.  # noqa: E501
        :type: int
        """

        self._response_time_ms = response_time_ms

    @property
    def error_message(self):
        """Gets the error_message of this ExternalServiceLiveStatusExt.  # noqa: E501


        :return: The error_message of this ExternalServiceLiveStatusExt.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this ExternalServiceLiveStatusExt.


        :param error_message: The error_message of this ExternalServiceLiveStatusExt.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def last_check(self):
        """Gets the last_check of this ExternalServiceLiveStatusExt.  # noqa: E501


        :return: The last_check of this ExternalServiceLiveStatusExt.  # noqa: E501
        :rtype: datetime
        """
        return self._last_check

    @last_check.setter
    def last_check(self, last_check):
        """Sets the last_check of this ExternalServiceLiveStatusExt.


        :param last_check: The last_check of this ExternalServiceLiveStatusExt.  # noqa: E501
        :type: datetime
        """

        self._last_check = last_check

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalServiceLiveStatusExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalServiceLiveStatusExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
