# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExternalServicesReportExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'live_status': 'list[ExternalServiceLiveStatusExt]',
        'statistics': 'list[ExternalServiceStatisticsExt]'
    }

    attribute_map = {
        'live_status': 'LiveStatus',
        'statistics': 'Statistics'
    }

    def __init__(self, live_status=None, statistics=None):  # noqa: E501
        """ExternalServicesReportExt - a model defined in Swagger"""  # noqa: E501
        self._live_status = None
        self._statistics = None
        self.discriminator = None
        if live_status is not None:
            self.live_status = live_status
        if statistics is not None:
            self.statistics = statistics

    @property
    def live_status(self):
        """Gets the live_status of this ExternalServicesReportExt.  # noqa: E501


        :return: The live_status of this ExternalServicesReportExt.  # noqa: E501
        :rtype: list[ExternalServiceLiveStatusExt]
        """
        return self._live_status

    @live_status.setter
    def live_status(self, live_status):
        """Sets the live_status of this ExternalServicesReportExt.


        :param live_status: The live_status of this ExternalServicesReportExt.  # noqa: E501
        :type: list[ExternalServiceLiveStatusExt]
        """

        self._live_status = live_status

    @property
    def statistics(self):
        """Gets the statistics of this ExternalServicesReportExt.  # noqa: E501


        :return: The statistics of this ExternalServicesReportExt.  # noqa: E501
        :rtype: list[ExternalServiceStatisticsExt]
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics):
        """Sets the statistics of this ExternalServicesReportExt.


        :param statistics: The statistics of this ExternalServicesReportExt.  # noqa: E501
        :type: list[ExternalServiceStatisticsExt]
        """

        self._statistics = statistics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalServicesReportExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalServicesReportExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
