# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetExternalServicesStatisticsModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_code': 'str',
        '_from': 'datetime',
        'to': 'datetime',
        'service_name': 'str',
        'cluster_id': 'int'
    }

    attribute_map = {
        'session_code': 'SessionCode',
        '_from': 'From',
        'to': 'To',
        'service_name': 'ServiceName',
        'cluster_id': 'ClusterId'
    }

    def __init__(self, session_code=None, _from=None, to=None, service_name=None, cluster_id=None):  # noqa: E501
        """GetExternalServicesStatisticsModel - a model defined in Swagger"""  # noqa: E501
        self._session_code = None
        self.__from = None
        self._to = None
        self._service_name = None
        self._cluster_id = None
        self.discriminator = None
        if session_code is not None:
            self.session_code = session_code
        if _from is not None:
            self._from = _from
        if to is not None:
            self.to = to
        if service_name is not None:
            self.service_name = service_name
        if cluster_id is not None:
            self.cluster_id = cluster_id

    @property
    def session_code(self):
        """Gets the session_code of this GetExternalServicesStatisticsModel.  # noqa: E501

        Session code  # noqa: E501

        :return: The session_code of this GetExternalServicesStatisticsModel.  # noqa: E501
        :rtype: str
        """
        return self._session_code

    @session_code.setter
    def session_code(self, session_code):
        """Sets the session_code of this GetExternalServicesStatisticsModel.

        Session code  # noqa: E501

        :param session_code: The session_code of this GetExternalServicesStatisticsModel.  # noqa: E501
        :type: str
        """

        self._session_code = session_code

    @property
    def _from(self):
        """Gets the _from of this GetExternalServicesStatisticsModel.  # noqa: E501

        Start of the statistics time window (UTC)  # noqa: E501

        :return: The _from of this GetExternalServicesStatisticsModel.  # noqa: E501
        :rtype: datetime
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this GetExternalServicesStatisticsModel.

        Start of the statistics time window (UTC)  # noqa: E501

        :param _from: The _from of this GetExternalServicesStatisticsModel.  # noqa: E501
        :type: datetime
        """

        self.__from = _from

    @property
    def to(self):
        """Gets the to of this GetExternalServicesStatisticsModel.  # noqa: E501

        End of the statistics time window (UTC)  # noqa: E501

        :return: The to of this GetExternalServicesStatisticsModel.  # noqa: E501
        :rtype: datetime
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this GetExternalServicesStatisticsModel.

        End of the statistics time window (UTC)  # noqa: E501

        :param to: The to of this GetExternalServicesStatisticsModel.  # noqa: E501
        :type: datetime
        """

        self._to = to

    @property
    def service_name(self):
        """Gets the service_name of this GetExternalServicesStatisticsModel.  # noqa: E501

        Optional filter by service name  # noqa: E501

        :return: The service_name of this GetExternalServicesStatisticsModel.  # noqa: E501
        :rtype: str
        """
        return self._service_name

    @service_name.setter
    def service_name(self, service_name):
        """Sets the service_name of this GetExternalServicesStatisticsModel.

        Optional filter by service name  # noqa: E501

        :param service_name: The service_name of this GetExternalServicesStatisticsModel.  # noqa: E501
        :type: str
        """

        self._service_name = service_name

    @property
    def cluster_id(self):
        """Gets the cluster_id of this GetExternalServicesStatisticsModel.  # noqa: E501

        Optional filter by cluster ID  # noqa: E501

        :return: The cluster_id of this GetExternalServicesStatisticsModel.  # noqa: E501
        :rtype: int
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this GetExternalServicesStatisticsModel.

        Optional filter by cluster ID  # noqa: E501

        :param cluster_id: The cluster_id of this GetExternalServicesStatisticsModel.  # noqa: E501
        :type: int
        """

        self._cluster_id = cluster_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetExternalServicesStatisticsModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetExternalServicesStatisticsModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
