# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetJobsMonitoringModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_code': 'str',
        'page_size': 'int',
        'last_job_id': 'int'
    }

    attribute_map = {
        'session_code': 'SessionCode',
        'page_size': 'PageSize',
        'last_job_id': 'LastJobId'
    }

    def __init__(self, session_code=None, page_size=None, last_job_id=None):  # noqa: E501
        """GetJobsMonitoringModel - a model defined in Swagger"""  # noqa: E501
        self._session_code = None
        self._page_size = None
        self._last_job_id = None
        self.discriminator = None
        if session_code is not None:
            self.session_code = session_code
        if page_size is not None:
            self.page_size = page_size
        if last_job_id is not None:
            self.last_job_id = last_job_id

    @property
    def session_code(self):
        """Gets the session_code of this GetJobsMonitoringModel.  # noqa: E501

        Session code  # noqa: E501

        :return: The session_code of this GetJobsMonitoringModel.  # noqa: E501
        :rtype: str
        """
        return self._session_code

    @session_code.setter
    def session_code(self, session_code):
        """Sets the session_code of this GetJobsMonitoringModel.

        Session code  # noqa: E501

        :param session_code: The session_code of this GetJobsMonitoringModel.  # noqa: E501
        :type: str
        """

        self._session_code = session_code

    @property
    def page_size(self):
        """Gets the page_size of this GetJobsMonitoringModel.  # noqa: E501

        Number of jobs per page (1–200)  # noqa: E501

        :return: The page_size of this GetJobsMonitoringModel.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this GetJobsMonitoringModel.

        Number of jobs per page (1–200)  # noqa: E501

        :param page_size: The page_size of this GetJobsMonitoringModel.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def last_job_id(self):
        """Gets the last_job_id of this GetJobsMonitoringModel.  # noqa: E501

        Cursor for keyset pagination – Id from the previous page's NextCursorId  # noqa: E501

        :return: The last_job_id of this GetJobsMonitoringModel.  # noqa: E501
        :rtype: int
        """
        return self._last_job_id

    @last_job_id.setter
    def last_job_id(self, last_job_id):
        """Sets the last_job_id of this GetJobsMonitoringModel.

        Cursor for keyset pagination – Id from the previous page's NextCursorId  # noqa: E501

        :param last_job_id: The last_job_id of this GetJobsMonitoringModel.  # noqa: E501
        :type: int
        """

        self._last_job_id = last_job_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetJobsMonitoringModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetJobsMonitoringModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
