# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobMonitoringExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'state': 'str',
        'submitted_by': 'str',
        'project': 'str',
        'cluster': 'str',
        'creation_time': 'datetime',
        'submit_time': 'datetime',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'total_allocated_time': 'float',
        'waiting_limit': 'int',
        'notification_email': 'str',
        'phone_number': 'str',
        'notify_on_abort': 'bool',
        'notify_on_finish': 'bool',
        'notify_on_start': 'bool',
        'reservation': 'str',
        'tasks': 'list[JobMonitoringTaskExt]'
    }

    attribute_map = {
        'id': 'Id',
        'name': 'Name',
        'state': 'State',
        'submitted_by': 'SubmittedBy',
        'project': 'Project',
        'cluster': 'Cluster',
        'creation_time': 'CreationTime',
        'submit_time': 'SubmitTime',
        'start_time': 'StartTime',
        'end_time': 'EndTime',
        'total_allocated_time': 'TotalAllocatedTime',
        'waiting_limit': 'WaitingLimit',
        'notification_email': 'NotificationEmail',
        'phone_number': 'PhoneNumber',
        'notify_on_abort': 'NotifyOnAbort',
        'notify_on_finish': 'NotifyOnFinish',
        'notify_on_start': 'NotifyOnStart',
        'reservation': 'Reservation',
        'tasks': 'Tasks'
    }

    def __init__(self, id=None, name=None, state=None, submitted_by=None, project=None, cluster=None, creation_time=None, submit_time=None, start_time=None, end_time=None, total_allocated_time=None, waiting_limit=None, notification_email=None, phone_number=None, notify_on_abort=None, notify_on_finish=None, notify_on_start=None, reservation=None, tasks=None):  # noqa: E501
        """JobMonitoringExt - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._state = None
        self._submitted_by = None
        self._project = None
        self._cluster = None
        self._creation_time = None
        self._submit_time = None
        self._start_time = None
        self._end_time = None
        self._total_allocated_time = None
        self._waiting_limit = None
        self._notification_email = None
        self._phone_number = None
        self._notify_on_abort = None
        self._notify_on_finish = None
        self._notify_on_start = None
        self._reservation = None
        self._tasks = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if state is not None:
            self.state = state
        if submitted_by is not None:
            self.submitted_by = submitted_by
        if project is not None:
            self.project = project
        if cluster is not None:
            self.cluster = cluster
        if creation_time is not None:
            self.creation_time = creation_time
        if submit_time is not None:
            self.submit_time = submit_time
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if total_allocated_time is not None:
            self.total_allocated_time = total_allocated_time
        if waiting_limit is not None:
            self.waiting_limit = waiting_limit
        if notification_email is not None:
            self.notification_email = notification_email
        if phone_number is not None:
            self.phone_number = phone_number
        if notify_on_abort is not None:
            self.notify_on_abort = notify_on_abort
        if notify_on_finish is not None:
            self.notify_on_finish = notify_on_finish
        if notify_on_start is not None:
            self.notify_on_start = notify_on_start
        if reservation is not None:
            self.reservation = reservation
        if tasks is not None:
            self.tasks = tasks

    @property
    def id(self):
        """Gets the id of this JobMonitoringExt.  # noqa: E501


        :return: The id of this JobMonitoringExt.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this JobMonitoringExt.


        :param id: The id of this JobMonitoringExt.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this JobMonitoringExt.  # noqa: E501


        :return: The name of this JobMonitoringExt.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this JobMonitoringExt.


        :param name: The name of this JobMonitoringExt.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def state(self):
        """Gets the state of this JobMonitoringExt.  # noqa: E501


        :return: The state of this JobMonitoringExt.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this JobMonitoringExt.


        :param state: The state of this JobMonitoringExt.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def submitted_by(self):
        """Gets the submitted_by of this JobMonitoringExt.  # noqa: E501


        :return: The submitted_by of this JobMonitoringExt.  # noqa: E501
        :rtype: str
        """
        return self._submitted_by

    @submitted_by.setter
    def submitted_by(self, submitted_by):
        """Sets the submitted_by of this JobMonitoringExt.


        :param submitted_by: The submitted_by of this JobMonitoringExt.  # noqa: E501
        :type: str
        """

        self._submitted_by = submitted_by

    @property
    def project(self):
        """Gets the project of this JobMonitoringExt.  # noqa: E501


        :return: The project of this JobMonitoringExt.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this JobMonitoringExt.


        :param project: The project of this JobMonitoringExt.  # noqa: E501
        :type: str
        """

        self._project = project

    @property
    def cluster(self):
        """Gets the cluster of this JobMonitoringExt.  # noqa: E501


        :return: The cluster of this JobMonitoringExt.  # noqa: E501
        :rtype: str
        """
        return self._cluster

    @cluster.setter
    def cluster(self, cluster):
        """Sets the cluster of this JobMonitoringExt.


        :param cluster: The cluster of this JobMonitoringExt.  # noqa: E501
        :type: str
        """

        self._cluster = cluster

    @property
    def creation_time(self):
        """Gets the creation_time of this JobMonitoringExt.  # noqa: E501


        :return: The creation_time of this JobMonitoringExt.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_time

    @creation_time.setter
    def creation_time(self, creation_time):
        """Sets the creation_time of this JobMonitoringExt.


        :param creation_time: The creation_time of this JobMonitoringExt.  # noqa: E501
        :type: datetime
        """

        self._creation_time = creation_time

    @property
    def submit_time(self):
        """Gets the submit_time of this JobMonitoringExt.  # noqa: E501


        :return: The submit_time of this JobMonitoringExt.  # noqa: E501
        :rtype: datetime
        """
        return self._submit_time

    @submit_time.setter
    def submit_time(self, submit_time):
        """Sets the submit_time of this JobMonitoringExt.


        :param submit_time: The submit_time of this JobMonitoringExt.  # noqa: E501
        :type: datetime
        """

        self._submit_time = submit_time

    @property
    def start_time(self):
        """Gets the start_time of this JobMonitoringExt.  # noqa: E501


        :return: The start_time of this JobMonitoringExt.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this JobMonitoringExt.


        :param start_time: The start_time of this JobMonitoringExt.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this JobMonitoringExt.  # noqa: E501


        :return: The end_time of this JobMonitoringExt.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this JobMonitoringExt.


        :param end_time: The end_time of this JobMonitoringExt.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    @property
    def total_allocated_time(self):
        """Gets the total_allocated_time of this JobMonitoringExt.  # noqa: E501


        :return: The total_allocated_time of this JobMonitoringExt.  # noqa: E501
        :rtype: float
        """
        return self._total_allocated_time

    @total_allocated_time.setter
    def total_allocated_time(self, total_allocated_time):
        """Sets the total_allocated_time of this JobMonitoringExt.


        :param total_allocated_time: The total_allocated_time of this JobMonitoringExt.  # noqa: E501
        :type: float
        """

        self._total_allocated_time = total_allocated_time

    @property
    def waiting_limit(self):
        """Gets the waiting_limit of this JobMonitoringExt.  # noqa: E501


        :return: The waiting_limit of this JobMonitoringExt.  # noqa: E501
        :rtype: int
        """
        return self._waiting_limit

    @waiting_limit.setter
    def waiting_limit(self, waiting_limit):
        """Sets the waiting_limit of this JobMonitoringExt.


        :param waiting_limit: The waiting_limit of this JobMonitoringExt.  # noqa: E501
        :type: int
        """

        self._waiting_limit = waiting_limit

    @property
    def notification_email(self):
        """Gets the notification_email of this JobMonitoringExt.  # noqa: E501


        :return: The notification_email of this JobMonitoringExt.  # noqa: E501
        :rtype: str
        """
        return self._notification_email

    @notification_email.setter
    def notification_email(self, notification_email):
        """Sets the notification_email of this JobMonitoringExt.


        :param notification_email: The notification_email of this JobMonitoringExt.  # noqa: E501
        :type: str
        """

        self._notification_email = notification_email

    @property
    def phone_number(self):
        """Gets the phone_number of this JobMonitoringExt.  # noqa: E501


        :return: The phone_number of this JobMonitoringExt.  # noqa: E501
        :rtype: str
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this JobMonitoringExt.


        :param phone_number: The phone_number of this JobMonitoringExt.  # noqa: E501
        :type: str
        """

        self._phone_number = phone_number

    @property
    def notify_on_abort(self):
        """Gets the notify_on_abort of this JobMonitoringExt.  # noqa: E501


        :return: The notify_on_abort of this JobMonitoringExt.  # noqa: E501
        :rtype: bool
        """
        return self._notify_on_abort

    @notify_on_abort.setter
    def notify_on_abort(self, notify_on_abort):
        """Sets the notify_on_abort of this JobMonitoringExt.


        :param notify_on_abort: The notify_on_abort of this JobMonitoringExt.  # noqa: E501
        :type: bool
        """

        self._notify_on_abort = notify_on_abort

    @property
    def notify_on_finish(self):
        """Gets the notify_on_finish of this JobMonitoringExt.  # noqa: E501


        :return: The notify_on_finish of this JobMonitoringExt.  # noqa: E501
        :rtype: bool
        """
        return self._notify_on_finish

    @notify_on_finish.setter
    def notify_on_finish(self, notify_on_finish):
        """Sets the notify_on_finish of this JobMonitoringExt.


        :param notify_on_finish: The notify_on_finish of this JobMonitoringExt.  # noqa: E501
        :type: bool
        """

        self._notify_on_finish = notify_on_finish

    @property
    def notify_on_start(self):
        """Gets the notify_on_start of this JobMonitoringExt.  # noqa: E501


        :return: The notify_on_start of this JobMonitoringExt.  # noqa: E501
        :rtype: bool
        """
        return self._notify_on_start

    @notify_on_start.setter
    def notify_on_start(self, notify_on_start):
        """Sets the notify_on_start of this JobMonitoringExt.


        :param notify_on_start: The notify_on_start of this JobMonitoringExt.  # noqa: E501
        :type: bool
        """

        self._notify_on_start = notify_on_start

    @property
    def reservation(self):
        """Gets the reservation of this JobMonitoringExt.  # noqa: E501


        :return: The reservation of this JobMonitoringExt.  # noqa: E501
        :rtype: str
        """
        return self._reservation

    @reservation.setter
    def reservation(self, reservation):
        """Sets the reservation of this JobMonitoringExt.


        :param reservation: The reservation of this JobMonitoringExt.  # noqa: E501
        :type: str
        """

        self._reservation = reservation

    @property
    def tasks(self):
        """Gets the tasks of this JobMonitoringExt.  # noqa: E501


        :return: The tasks of this JobMonitoringExt.  # noqa: E501
        :rtype: list[JobMonitoringTaskExt]
        """
        return self._tasks

    @tasks.setter
    def tasks(self, tasks):
        """Sets the tasks of this JobMonitoringExt.


        :param tasks: The tasks of this JobMonitoringExt.  # noqa: E501
        :type: list[JobMonitoringTaskExt]
        """

        self._tasks = tasks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobMonitoringExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobMonitoringExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
