# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobExternalServiceLogExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'service_name': 'str',
        'service_type': 'str',
        'protocol': 'str',
        'endpoint_or_host': 'str',
        'port': 'int',
        'operation': 'str',
        'timestamp': 'datetime',
        'is_success': 'bool',
        'response_time_ms': 'int',
        'status_code': 'str',
        'error_message': 'str',
        'job_id': 'int',
        'task_id': 'int',
        'cluster_id': 'int',
        'request_id': 'str',
        'source': 'str'
    }

    attribute_map = {
        'id': 'Id',
        'service_name': 'ServiceName',
        'service_type': 'ServiceType',
        'protocol': 'Protocol',
        'endpoint_or_host': 'EndpointOrHost',
        'port': 'Port',
        'operation': 'Operation',
        'timestamp': 'Timestamp',
        'is_success': 'IsSuccess',
        'response_time_ms': 'ResponseTimeMs',
        'status_code': 'StatusCode',
        'error_message': 'ErrorMessage',
        'job_id': 'JobId',
        'task_id': 'TaskId',
        'cluster_id': 'ClusterId',
        'request_id': 'RequestId',
        'source': 'Source'
    }

    def __init__(self, id=None, service_name=None, service_type=None, protocol=None, endpoint_or_host=None, port=None, operation=None, timestamp=None, is_success=None, response_time_ms=None, status_code=None, error_message=None, job_id=None, task_id=None, cluster_id=None, request_id=None, source=None):  # noqa: E501
        """JobExternalServiceLogExt - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._service_name = None
        self._service_type = None
        self._protocol = None
        self._endpoint_or_host = None
        self._port = None
        self._operation = None
        self._timestamp = None
        self._is_success = None
        self._response_time_ms = None
        self._status_code = None
        self._error_message = None
        self._job_id = None
        self._task_id = None
        self._cluster_id = None
        self._request_id = None
        self._source = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if service_name is not None:
            self.service_name = service_name
        if service_type is not None:
            self.service_type = service_type
        if protocol is not None:
            self.protocol = protocol
        if endpoint_or_host is not None:
            self.endpoint_or_host = endpoint_or_host
        if port is not None:
            self.port = port
        if operation is not None:
            self.operation = operation
        if timestamp is not None:
            self.timestamp = timestamp
        if is_success is not None:
            self.is_success = is_success
        if response_time_ms is not None:
            self.response_time_ms = response_time_ms
        if status_code is not None:
            self.status_code = status_code
        if error_message is not None:
            self.error_message = error_message
        if job_id is not None:
            self.job_id = job_id
        if task_id is not None:
            self.task_id = task_id
        if cluster_id is not None:
            self.cluster_id = cluster_id
        if request_id is not None:
            self.request_id = request_id
        if source is not None:
            self.source = source

    @property
    def id(self):
        """Gets the id of this JobExternalServiceLogExt.  # noqa: E501


        :return: The id of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this JobExternalServiceLogExt.


        :param id: The id of this JobExternalServiceLogExt.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def service_name(self):
        """Gets the service_name of this JobExternalServiceLogExt.  # noqa: E501


        :return: The service_name of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: str
        """
        return self._service_name

    @service_name.setter
    def service_name(self, service_name):
        """Sets the service_name of this JobExternalServiceLogExt.


        :param service_name: The service_name of this JobExternalServiceLogExt.  # noqa: E501
        :type: str
        """

        self._service_name = service_name

    @property
    def service_type(self):
        """Gets the service_type of this JobExternalServiceLogExt.  # noqa: E501


        :return: The service_type of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: str
        """
        return self._service_type

    @service_type.setter
    def service_type(self, service_type):
        """Sets the service_type of this JobExternalServiceLogExt.


        :param service_type: The service_type of this JobExternalServiceLogExt.  # noqa: E501
        :type: str
        """

        self._service_type = service_type

    @property
    def protocol(self):
        """Gets the protocol of this JobExternalServiceLogExt.  # noqa: E501


        :return: The protocol of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """Sets the protocol of this JobExternalServiceLogExt.


        :param protocol: The protocol of this JobExternalServiceLogExt.  # noqa: E501
        :type: str
        """

        self._protocol = protocol

    @property
    def endpoint_or_host(self):
        """Gets the endpoint_or_host of this JobExternalServiceLogExt.  # noqa: E501


        :return: The endpoint_or_host of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: str
        """
        return self._endpoint_or_host

    @endpoint_or_host.setter
    def endpoint_or_host(self, endpoint_or_host):
        """Sets the endpoint_or_host of this JobExternalServiceLogExt.


        :param endpoint_or_host: The endpoint_or_host of this JobExternalServiceLogExt.  # noqa: E501
        :type: str
        """

        self._endpoint_or_host = endpoint_or_host

    @property
    def port(self):
        """Gets the port of this JobExternalServiceLogExt.  # noqa: E501


        :return: The port of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this JobExternalServiceLogExt.


        :param port: The port of this JobExternalServiceLogExt.  # noqa: E501
        :type: int
        """

        self._port = port

    @property
    def operation(self):
        """Gets the operation of this JobExternalServiceLogExt.  # noqa: E501


        :return: The operation of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this JobExternalServiceLogExt.


        :param operation: The operation of this JobExternalServiceLogExt.  # noqa: E501
        :type: str
        """

        self._operation = operation

    @property
    def timestamp(self):
        """Gets the timestamp of this JobExternalServiceLogExt.  # noqa: E501


        :return: The timestamp of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this JobExternalServiceLogExt.


        :param timestamp: The timestamp of this JobExternalServiceLogExt.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    @property
    def is_success(self):
        """Gets the is_success of this JobExternalServiceLogExt.  # noqa: E501


        :return: The is_success of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: bool
        """
        return self._is_success

    @is_success.setter
    def is_success(self, is_success):
        """Sets the is_success of this JobExternalServiceLogExt.


        :param is_success: The is_success of this JobExternalServiceLogExt.  # noqa: E501
        :type: bool
        """

        self._is_success = is_success

    @property
    def response_time_ms(self):
        """Gets the response_time_ms of this JobExternalServiceLogExt.  # noqa: E501


        :return: The response_time_ms of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: int
        """
        return self._response_time_ms

    @response_time_ms.setter
    def response_time_ms(self, response_time_ms):
        """Sets the response_time_ms of this JobExternalServiceLogExt.


        :param response_time_ms: The response_time_ms of this JobExternalServiceLogExt.  # noqa: E501
        :type: int
        """

        self._response_time_ms = response_time_ms

    @property
    def status_code(self):
        """Gets the status_code of this JobExternalServiceLogExt.  # noqa: E501


        :return: The status_code of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: str
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this JobExternalServiceLogExt.


        :param status_code: The status_code of this JobExternalServiceLogExt.  # noqa: E501
        :type: str
        """

        self._status_code = status_code

    @property
    def error_message(self):
        """Gets the error_message of this JobExternalServiceLogExt.  # noqa: E501


        :return: The error_message of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this JobExternalServiceLogExt.


        :param error_message: The error_message of this JobExternalServiceLogExt.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def job_id(self):
        """Gets the job_id of this JobExternalServiceLogExt.  # noqa: E501


        :return: The job_id of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: int
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this JobExternalServiceLogExt.


        :param job_id: The job_id of this JobExternalServiceLogExt.  # noqa: E501
        :type: int
        """

        self._job_id = job_id

    @property
    def task_id(self):
        """Gets the task_id of this JobExternalServiceLogExt.  # noqa: E501


        :return: The task_id of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: int
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this JobExternalServiceLogExt.


        :param task_id: The task_id of this JobExternalServiceLogExt.  # noqa: E501
        :type: int
        """

        self._task_id = task_id

    @property
    def cluster_id(self):
        """Gets the cluster_id of this JobExternalServiceLogExt.  # noqa: E501


        :return: The cluster_id of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: int
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this JobExternalServiceLogExt.


        :param cluster_id: The cluster_id of this JobExternalServiceLogExt.  # noqa: E501
        :type: int
        """

        self._cluster_id = cluster_id

    @property
    def request_id(self):
        """Gets the request_id of this JobExternalServiceLogExt.  # noqa: E501


        :return: The request_id of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this JobExternalServiceLogExt.


        :param request_id: The request_id of this JobExternalServiceLogExt.  # noqa: E501
        :type: str
        """

        self._request_id = request_id

    @property
    def source(self):
        """Gets the source of this JobExternalServiceLogExt.  # noqa: E501


        :return: The source of this JobExternalServiceLogExt.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this JobExternalServiceLogExt.


        :param source: The source of this JobExternalServiceLogExt.  # noqa: E501
        :type: str
        """

        self._source = source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobExternalServiceLogExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobExternalServiceLogExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
