# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobMonitoringTaskExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'state': 'str',
        'scheduled_job_id': 'str',
        'allocated_cores': 'int',
        'allocated_gpus': 'int',
        'allocated_time': 'float',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'error_message': 'str',
        'priority': 'str',
        'reason': 'str',
        'all_parameters': 'str',
        'min_cores': 'int',
        'max_cores': 'int',
        'walltime_limit': 'int',
        'memory': 'int',
        'memory_per_cpu': 'int',
        'memory_per_gpu': 'int',
        'is_exclusive': 'bool',
        'is_rerunnable': 'bool',
        'standard_input_file': 'str',
        'standard_output_file': 'str',
        'standard_error_file': 'str',
        'local_directory': 'str',
        'cluster_task_subdirectory': 'str',
        'cpu_hyper_threading': 'bool',
        'command_template_id': 'int',
        'command_template_name': 'str',
        'command_parameter_values': 'list[CommandTemplateParameterValueExt]',
        'environment_variables': 'list[EnvironmentVariableExt]'
    }

    attribute_map = {
        'id': 'Id',
        'name': 'Name',
        'state': 'State',
        'scheduled_job_id': 'ScheduledJobId',
        'allocated_cores': 'AllocatedCores',
        'allocated_gpus': 'AllocatedGpus',
        'allocated_time': 'AllocatedTime',
        'start_time': 'StartTime',
        'end_time': 'EndTime',
        'error_message': 'ErrorMessage',
        'priority': 'Priority',
        'reason': 'Reason',
        'all_parameters': 'AllParameters',
        'min_cores': 'MinCores',
        'max_cores': 'MaxCores',
        'walltime_limit': 'WalltimeLimit',
        'memory': 'Memory',
        'memory_per_cpu': 'MemoryPerCPU',
        'memory_per_gpu': 'MemoryPerGPU',
        'is_exclusive': 'IsExclusive',
        'is_rerunnable': 'IsRerunnable',
        'standard_input_file': 'StandardInputFile',
        'standard_output_file': 'StandardOutputFile',
        'standard_error_file': 'StandardErrorFile',
        'local_directory': 'LocalDirectory',
        'cluster_task_subdirectory': 'ClusterTaskSubdirectory',
        'cpu_hyper_threading': 'CpuHyperThreading',
        'command_template_id': 'CommandTemplateId',
        'command_template_name': 'CommandTemplateName',
        'command_parameter_values': 'CommandParameterValues',
        'environment_variables': 'EnvironmentVariables'
    }

    def __init__(self, id=None, name=None, state=None, scheduled_job_id=None, allocated_cores=None, allocated_gpus=None, allocated_time=None, start_time=None, end_time=None, error_message=None, priority=None, reason=None, all_parameters=None, min_cores=None, max_cores=None, walltime_limit=None, memory=None, memory_per_cpu=None, memory_per_gpu=None, is_exclusive=None, is_rerunnable=None, standard_input_file=None, standard_output_file=None, standard_error_file=None, local_directory=None, cluster_task_subdirectory=None, cpu_hyper_threading=None, command_template_id=None, command_template_name=None, command_parameter_values=None, environment_variables=None):  # noqa: E501
        """JobMonitoringTaskExt - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._state = None
        self._scheduled_job_id = None
        self._allocated_cores = None
        self._allocated_gpus = None
        self._allocated_time = None
        self._start_time = None
        self._end_time = None
        self._error_message = None
        self._priority = None
        self._reason = None
        self._all_parameters = None
        self._min_cores = None
        self._max_cores = None
        self._walltime_limit = None
        self._memory = None
        self._memory_per_cpu = None
        self._memory_per_gpu = None
        self._is_exclusive = None
        self._is_rerunnable = None
        self._standard_input_file = None
        self._standard_output_file = None
        self._standard_error_file = None
        self._local_directory = None
        self._cluster_task_subdirectory = None
        self._cpu_hyper_threading = None
        self._command_template_id = None
        self._command_template_name = None
        self._command_parameter_values = None
        self._environment_variables = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if state is not None:
            self.state = state
        if scheduled_job_id is not None:
            self.scheduled_job_id = scheduled_job_id
        if allocated_cores is not None:
            self.allocated_cores = allocated_cores
        if allocated_gpus is not None:
            self.allocated_gpus = allocated_gpus
        if allocated_time is not None:
            self.allocated_time = allocated_time
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if error_message is not None:
            self.error_message = error_message
        if priority is not None:
            self.priority = priority
        if reason is not None:
            self.reason = reason
        if all_parameters is not None:
            self.all_parameters = all_parameters
        if min_cores is not None:
            self.min_cores = min_cores
        if max_cores is not None:
            self.max_cores = max_cores
        if walltime_limit is not None:
            self.walltime_limit = walltime_limit
        if memory is not None:
            self.memory = memory
        if memory_per_cpu is not None:
            self.memory_per_cpu = memory_per_cpu
        if memory_per_gpu is not None:
            self.memory_per_gpu = memory_per_gpu
        if is_exclusive is not None:
            self.is_exclusive = is_exclusive
        if is_rerunnable is not None:
            self.is_rerunnable = is_rerunnable
        if standard_input_file is not None:
            self.standard_input_file = standard_input_file
        if standard_output_file is not None:
            self.standard_output_file = standard_output_file
        if standard_error_file is not None:
            self.standard_error_file = standard_error_file
        if local_directory is not None:
            self.local_directory = local_directory
        if cluster_task_subdirectory is not None:
            self.cluster_task_subdirectory = cluster_task_subdirectory
        if cpu_hyper_threading is not None:
            self.cpu_hyper_threading = cpu_hyper_threading
        if command_template_id is not None:
            self.command_template_id = command_template_id
        if command_template_name is not None:
            self.command_template_name = command_template_name
        if command_parameter_values is not None:
            self.command_parameter_values = command_parameter_values
        if environment_variables is not None:
            self.environment_variables = environment_variables

    @property
    def id(self):
        """Gets the id of this JobMonitoringTaskExt.  # noqa: E501


        :return: The id of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this JobMonitoringTaskExt.


        :param id: The id of this JobMonitoringTaskExt.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this JobMonitoringTaskExt.  # noqa: E501


        :return: The name of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this JobMonitoringTaskExt.


        :param name: The name of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def state(self):
        """Gets the state of this JobMonitoringTaskExt.  # noqa: E501


        :return: The state of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this JobMonitoringTaskExt.


        :param state: The state of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def scheduled_job_id(self):
        """Gets the scheduled_job_id of this JobMonitoringTaskExt.  # noqa: E501


        :return: The scheduled_job_id of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._scheduled_job_id

    @scheduled_job_id.setter
    def scheduled_job_id(self, scheduled_job_id):
        """Sets the scheduled_job_id of this JobMonitoringTaskExt.


        :param scheduled_job_id: The scheduled_job_id of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._scheduled_job_id = scheduled_job_id

    @property
    def allocated_cores(self):
        """Gets the allocated_cores of this JobMonitoringTaskExt.  # noqa: E501


        :return: The allocated_cores of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: int
        """
        return self._allocated_cores

    @allocated_cores.setter
    def allocated_cores(self, allocated_cores):
        """Sets the allocated_cores of this JobMonitoringTaskExt.


        :param allocated_cores: The allocated_cores of this JobMonitoringTaskExt.  # noqa: E501
        :type: int
        """

        self._allocated_cores = allocated_cores

    @property
    def allocated_gpus(self):
        """Gets the allocated_gpus of this JobMonitoringTaskExt.  # noqa: E501


        :return: The allocated_gpus of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: int
        """
        return self._allocated_gpus

    @allocated_gpus.setter
    def allocated_gpus(self, allocated_gpus):
        """Sets the allocated_gpus of this JobMonitoringTaskExt.


        :param allocated_gpus: The allocated_gpus of this JobMonitoringTaskExt.  # noqa: E501
        :type: int
        """

        self._allocated_gpus = allocated_gpus

    @property
    def allocated_time(self):
        """Gets the allocated_time of this JobMonitoringTaskExt.  # noqa: E501


        :return: The allocated_time of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: float
        """
        return self._allocated_time

    @allocated_time.setter
    def allocated_time(self, allocated_time):
        """Sets the allocated_time of this JobMonitoringTaskExt.


        :param allocated_time: The allocated_time of this JobMonitoringTaskExt.  # noqa: E501
        :type: float
        """

        self._allocated_time = allocated_time

    @property
    def start_time(self):
        """Gets the start_time of this JobMonitoringTaskExt.  # noqa: E501


        :return: The start_time of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this JobMonitoringTaskExt.


        :param start_time: The start_time of this JobMonitoringTaskExt.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this JobMonitoringTaskExt.  # noqa: E501


        :return: The end_time of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this JobMonitoringTaskExt.


        :param end_time: The end_time of this JobMonitoringTaskExt.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    @property
    def error_message(self):
        """Gets the error_message of this JobMonitoringTaskExt.  # noqa: E501


        :return: The error_message of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this JobMonitoringTaskExt.


        :param error_message: The error_message of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def priority(self):
        """Gets the priority of this JobMonitoringTaskExt.  # noqa: E501


        :return: The priority of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this JobMonitoringTaskExt.


        :param priority: The priority of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._priority = priority

    @property
    def reason(self):
        """Gets the reason of this JobMonitoringTaskExt.  # noqa: E501


        :return: The reason of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this JobMonitoringTaskExt.


        :param reason: The reason of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._reason = reason

    @property
    def all_parameters(self):
        """Gets the all_parameters of this JobMonitoringTaskExt.  # noqa: E501


        :return: The all_parameters of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._all_parameters

    @all_parameters.setter
    def all_parameters(self, all_parameters):
        """Sets the all_parameters of this JobMonitoringTaskExt.


        :param all_parameters: The all_parameters of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._all_parameters = all_parameters

    @property
    def min_cores(self):
        """Gets the min_cores of this JobMonitoringTaskExt.  # noqa: E501


        :return: The min_cores of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: int
        """
        return self._min_cores

    @min_cores.setter
    def min_cores(self, min_cores):
        """Sets the min_cores of this JobMonitoringTaskExt.


        :param min_cores: The min_cores of this JobMonitoringTaskExt.  # noqa: E501
        :type: int
        """

        self._min_cores = min_cores

    @property
    def max_cores(self):
        """Gets the max_cores of this JobMonitoringTaskExt.  # noqa: E501


        :return: The max_cores of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: int
        """
        return self._max_cores

    @max_cores.setter
    def max_cores(self, max_cores):
        """Sets the max_cores of this JobMonitoringTaskExt.


        :param max_cores: The max_cores of this JobMonitoringTaskExt.  # noqa: E501
        :type: int
        """

        self._max_cores = max_cores

    @property
    def walltime_limit(self):
        """Gets the walltime_limit of this JobMonitoringTaskExt.  # noqa: E501


        :return: The walltime_limit of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: int
        """
        return self._walltime_limit

    @walltime_limit.setter
    def walltime_limit(self, walltime_limit):
        """Sets the walltime_limit of this JobMonitoringTaskExt.


        :param walltime_limit: The walltime_limit of this JobMonitoringTaskExt.  # noqa: E501
        :type: int
        """

        self._walltime_limit = walltime_limit

    @property
    def memory(self):
        """Gets the memory of this JobMonitoringTaskExt.  # noqa: E501


        :return: The memory of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: int
        """
        return self._memory

    @memory.setter
    def memory(self, memory):
        """Sets the memory of this JobMonitoringTaskExt.


        :param memory: The memory of this JobMonitoringTaskExt.  # noqa: E501
        :type: int
        """

        self._memory = memory

    @property
    def memory_per_cpu(self):
        """Gets the memory_per_cpu of this JobMonitoringTaskExt.  # noqa: E501


        :return: The memory_per_cpu of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: int
        """
        return self._memory_per_cpu

    @memory_per_cpu.setter
    def memory_per_cpu(self, memory_per_cpu):
        """Sets the memory_per_cpu of this JobMonitoringTaskExt.


        :param memory_per_cpu: The memory_per_cpu of this JobMonitoringTaskExt.  # noqa: E501
        :type: int
        """

        self._memory_per_cpu = memory_per_cpu

    @property
    def memory_per_gpu(self):
        """Gets the memory_per_gpu of this JobMonitoringTaskExt.  # noqa: E501


        :return: The memory_per_gpu of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: int
        """
        return self._memory_per_gpu

    @memory_per_gpu.setter
    def memory_per_gpu(self, memory_per_gpu):
        """Sets the memory_per_gpu of this JobMonitoringTaskExt.


        :param memory_per_gpu: The memory_per_gpu of this JobMonitoringTaskExt.  # noqa: E501
        :type: int
        """

        self._memory_per_gpu = memory_per_gpu

    @property
    def is_exclusive(self):
        """Gets the is_exclusive of this JobMonitoringTaskExt.  # noqa: E501


        :return: The is_exclusive of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: bool
        """
        return self._is_exclusive

    @is_exclusive.setter
    def is_exclusive(self, is_exclusive):
        """Sets the is_exclusive of this JobMonitoringTaskExt.


        :param is_exclusive: The is_exclusive of this JobMonitoringTaskExt.  # noqa: E501
        :type: bool
        """

        self._is_exclusive = is_exclusive

    @property
    def is_rerunnable(self):
        """Gets the is_rerunnable of this JobMonitoringTaskExt.  # noqa: E501


        :return: The is_rerunnable of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: bool
        """
        return self._is_rerunnable

    @is_rerunnable.setter
    def is_rerunnable(self, is_rerunnable):
        """Sets the is_rerunnable of this JobMonitoringTaskExt.


        :param is_rerunnable: The is_rerunnable of this JobMonitoringTaskExt.  # noqa: E501
        :type: bool
        """

        self._is_rerunnable = is_rerunnable

    @property
    def standard_input_file(self):
        """Gets the standard_input_file of this JobMonitoringTaskExt.  # noqa: E501


        :return: The standard_input_file of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._standard_input_file

    @standard_input_file.setter
    def standard_input_file(self, standard_input_file):
        """Sets the standard_input_file of this JobMonitoringTaskExt.


        :param standard_input_file: The standard_input_file of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._standard_input_file = standard_input_file

    @property
    def standard_output_file(self):
        """Gets the standard_output_file of this JobMonitoringTaskExt.  # noqa: E501


        :return: The standard_output_file of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._standard_output_file

    @standard_output_file.setter
    def standard_output_file(self, standard_output_file):
        """Sets the standard_output_file of this JobMonitoringTaskExt.


        :param standard_output_file: The standard_output_file of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._standard_output_file = standard_output_file

    @property
    def standard_error_file(self):
        """Gets the standard_error_file of this JobMonitoringTaskExt.  # noqa: E501


        :return: The standard_error_file of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._standard_error_file

    @standard_error_file.setter
    def standard_error_file(self, standard_error_file):
        """Sets the standard_error_file of this JobMonitoringTaskExt.


        :param standard_error_file: The standard_error_file of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._standard_error_file = standard_error_file

    @property
    def local_directory(self):
        """Gets the local_directory of this JobMonitoringTaskExt.  # noqa: E501


        :return: The local_directory of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._local_directory

    @local_directory.setter
    def local_directory(self, local_directory):
        """Sets the local_directory of this JobMonitoringTaskExt.


        :param local_directory: The local_directory of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._local_directory = local_directory

    @property
    def cluster_task_subdirectory(self):
        """Gets the cluster_task_subdirectory of this JobMonitoringTaskExt.  # noqa: E501


        :return: The cluster_task_subdirectory of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._cluster_task_subdirectory

    @cluster_task_subdirectory.setter
    def cluster_task_subdirectory(self, cluster_task_subdirectory):
        """Sets the cluster_task_subdirectory of this JobMonitoringTaskExt.


        :param cluster_task_subdirectory: The cluster_task_subdirectory of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._cluster_task_subdirectory = cluster_task_subdirectory

    @property
    def cpu_hyper_threading(self):
        """Gets the cpu_hyper_threading of this JobMonitoringTaskExt.  # noqa: E501


        :return: The cpu_hyper_threading of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: bool
        """
        return self._cpu_hyper_threading

    @cpu_hyper_threading.setter
    def cpu_hyper_threading(self, cpu_hyper_threading):
        """Sets the cpu_hyper_threading of this JobMonitoringTaskExt.


        :param cpu_hyper_threading: The cpu_hyper_threading of this JobMonitoringTaskExt.  # noqa: E501
        :type: bool
        """

        self._cpu_hyper_threading = cpu_hyper_threading

    @property
    def command_template_id(self):
        """Gets the command_template_id of this JobMonitoringTaskExt.  # noqa: E501


        :return: The command_template_id of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: int
        """
        return self._command_template_id

    @command_template_id.setter
    def command_template_id(self, command_template_id):
        """Sets the command_template_id of this JobMonitoringTaskExt.


        :param command_template_id: The command_template_id of this JobMonitoringTaskExt.  # noqa: E501
        :type: int
        """

        self._command_template_id = command_template_id

    @property
    def command_template_name(self):
        """Gets the command_template_name of this JobMonitoringTaskExt.  # noqa: E501


        :return: The command_template_name of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: str
        """
        return self._command_template_name

    @command_template_name.setter
    def command_template_name(self, command_template_name):
        """Sets the command_template_name of this JobMonitoringTaskExt.


        :param command_template_name: The command_template_name of this JobMonitoringTaskExt.  # noqa: E501
        :type: str
        """

        self._command_template_name = command_template_name

    @property
    def command_parameter_values(self):
        """Gets the command_parameter_values of this JobMonitoringTaskExt.  # noqa: E501


        :return: The command_parameter_values of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: list[CommandTemplateParameterValueExt]
        """
        return self._command_parameter_values

    @command_parameter_values.setter
    def command_parameter_values(self, command_parameter_values):
        """Sets the command_parameter_values of this JobMonitoringTaskExt.


        :param command_parameter_values: The command_parameter_values of this JobMonitoringTaskExt.  # noqa: E501
        :type: list[CommandTemplateParameterValueExt]
        """

        self._command_parameter_values = command_parameter_values

    @property
    def environment_variables(self):
        """Gets the environment_variables of this JobMonitoringTaskExt.  # noqa: E501


        :return: The environment_variables of this JobMonitoringTaskExt.  # noqa: E501
        :rtype: list[EnvironmentVariableExt]
        """
        return self._environment_variables

    @environment_variables.setter
    def environment_variables(self, environment_variables):
        """Sets the environment_variables of this JobMonitoringTaskExt.


        :param environment_variables: The environment_variables of this JobMonitoringTaskExt.  # noqa: E501
        :type: list[EnvironmentVariableExt]
        """

        self._environment_variables = environment_variables

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobMonitoringTaskExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobMonitoringTaskExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
