# coding: utf-8

"""
    py4heappe API

    Merged API documentation for py4heappe client  # noqa: E501

    OpenAPI spec version: v6.2.0
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ModifyAdaptorUserModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_code': 'str',
        'old_username': 'str',
        'new_username': 'str'
    }

    attribute_map = {
        'session_code': 'SessionCode',
        'old_username': 'OldUsername',
        'new_username': 'NewUsername'
    }

    def __init__(self, session_code=None, old_username=None, new_username=None):  # noqa: E501
        """ModifyAdaptorUserModel - a model defined in Swagger"""  # noqa: E501
        self._session_code = None
        self._old_username = None
        self._new_username = None
        self.discriminator = None
        if session_code is not None:
            self.session_code = session_code
        if old_username is not None:
            self.old_username = old_username
        if new_username is not None:
            self.new_username = new_username

    @property
    def session_code(self):
        """Gets the session_code of this ModifyAdaptorUserModel.  # noqa: E501

        Session code  # noqa: E501

        :return: The session_code of this ModifyAdaptorUserModel.  # noqa: E501
        :rtype: str
        """
        return self._session_code

    @session_code.setter
    def session_code(self, session_code):
        """Sets the session_code of this ModifyAdaptorUserModel.

        Session code  # noqa: E501

        :param session_code: The session_code of this ModifyAdaptorUserModel.  # noqa: E501
        :type: str
        """

        self._session_code = session_code

    @property
    def old_username(self):
        """Gets the old_username of this ModifyAdaptorUserModel.  # noqa: E501

        OldUsername  # noqa: E501

        :return: The old_username of this ModifyAdaptorUserModel.  # noqa: E501
        :rtype: str
        """
        return self._old_username

    @old_username.setter
    def old_username(self, old_username):
        """Sets the old_username of this ModifyAdaptorUserModel.

        OldUsername  # noqa: E501

        :param old_username: The old_username of this ModifyAdaptorUserModel.  # noqa: E501
        :type: str
        """

        self._old_username = old_username

    @property
    def new_username(self):
        """Gets the new_username of this ModifyAdaptorUserModel.  # noqa: E501

        NewUsername  # noqa: E501

        :return: The new_username of this ModifyAdaptorUserModel.  # noqa: E501
        :rtype: str
        """
        return self._new_username

    @new_username.setter
    def new_username(self, new_username):
        """Sets the new_username of this ModifyAdaptorUserModel.

        NewUsername  # noqa: E501

        :param new_username: The new_username of this ModifyAdaptorUserModel.  # noqa: E501
        :type: str
        """

        self._new_username = new_username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModifyAdaptorUserModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModifyAdaptorUserModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
