# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ModifyCredentialModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_id': 'int',
        'session_code': 'str',
        'adaptor_user_id': 'int',
        'old_username': 'str',
        'new_username': 'str',
        'new_password': 'str'
    }

    attribute_map = {
        'project_id': 'ProjectId',
        'session_code': 'SessionCode',
        'adaptor_user_id': 'AdaptorUserId',
        'old_username': 'OldUsername',
        'new_username': 'NewUsername',
        'new_password': 'NewPassword'
    }

    def __init__(self, project_id=None, session_code=None, adaptor_user_id=None, old_username=None, new_username=None, new_password=None):  # noqa: E501
        """ModifyCredentialModel - a model defined in Swagger"""  # noqa: E501
        self._project_id = None
        self._session_code = None
        self._adaptor_user_id = None
        self._old_username = None
        self._new_username = None
        self._new_password = None
        self.discriminator = None
        if project_id is not None:
            self.project_id = project_id
        if session_code is not None:
            self.session_code = session_code
        if adaptor_user_id is not None:
            self.adaptor_user_id = adaptor_user_id
        if old_username is not None:
            self.old_username = old_username
        if new_username is not None:
            self.new_username = new_username
        if new_password is not None:
            self.new_password = new_password

    @property
    def project_id(self):
        """Gets the project_id of this ModifyCredentialModel.  # noqa: E501

        Project id  # noqa: E501

        :return: The project_id of this ModifyCredentialModel.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this ModifyCredentialModel.

        Project id  # noqa: E501

        :param project_id: The project_id of this ModifyCredentialModel.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def session_code(self):
        """Gets the session_code of this ModifyCredentialModel.  # noqa: E501

        Session code  # noqa: E501

        :return: The session_code of this ModifyCredentialModel.  # noqa: E501
        :rtype: str
        """
        return self._session_code

    @session_code.setter
    def session_code(self, session_code):
        """Sets the session_code of this ModifyCredentialModel.

        Session code  # noqa: E501

        :param session_code: The session_code of this ModifyCredentialModel.  # noqa: E501
        :type: str
        """

        self._session_code = session_code

    @property
    def adaptor_user_id(self):
        """Gets the adaptor_user_id of this ModifyCredentialModel.  # noqa: E501

        Adaptor user id  # noqa: E501

        :return: The adaptor_user_id of this ModifyCredentialModel.  # noqa: E501
        :rtype: int
        """
        return self._adaptor_user_id

    @adaptor_user_id.setter
    def adaptor_user_id(self, adaptor_user_id):
        """Sets the adaptor_user_id of this ModifyCredentialModel.

        Adaptor user id  # noqa: E501

        :param adaptor_user_id: The adaptor_user_id of this ModifyCredentialModel.  # noqa: E501
        :type: int
        """

        self._adaptor_user_id = adaptor_user_id

    @property
    def old_username(self):
        """Gets the old_username of this ModifyCredentialModel.  # noqa: E501

        Old username  # noqa: E501

        :return: The old_username of this ModifyCredentialModel.  # noqa: E501
        :rtype: str
        """
        return self._old_username

    @old_username.setter
    def old_username(self, old_username):
        """Sets the old_username of this ModifyCredentialModel.

        Old username  # noqa: E501

        :param old_username: The old_username of this ModifyCredentialModel.  # noqa: E501
        :type: str
        """

        self._old_username = old_username

    @property
    def new_username(self):
        """Gets the new_username of this ModifyCredentialModel.  # noqa: E501

        New username  # noqa: E501

        :return: The new_username of this ModifyCredentialModel.  # noqa: E501
        :rtype: str
        """
        return self._new_username

    @new_username.setter
    def new_username(self, new_username):
        """Sets the new_username of this ModifyCredentialModel.

        New username  # noqa: E501

        :param new_username: The new_username of this ModifyCredentialModel.  # noqa: E501
        :type: str
        """

        self._new_username = new_username

    @property
    def new_password(self):
        """Gets the new_password of this ModifyCredentialModel.  # noqa: E501

        New password  # noqa: E501

        :return: The new_password of this ModifyCredentialModel.  # noqa: E501
        :rtype: str
        """
        return self._new_password

    @new_password.setter
    def new_password(self, new_password):
        """Sets the new_password of this ModifyCredentialModel.

        New password  # noqa: E501

        :param new_password: The new_password of this ModifyCredentialModel.  # noqa: E501
        :type: str
        """

        self._new_password = new_password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModifyCredentialModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModifyCredentialModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
