# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QSchedulerSessionInfoExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_id': 'int',
        'cluster_id': 'int',
        'project_id': 'int',
        'state': 'str',
        'created_at': 'datetime',
        'closed_at': 'datetime'
    }

    attribute_map = {
        'session_id': 'SessionId',
        'cluster_id': 'ClusterId',
        'project_id': 'ProjectId',
        'state': 'State',
        'created_at': 'CreatedAt',
        'closed_at': 'ClosedAt'
    }

    def __init__(self, session_id=None, cluster_id=None, project_id=None, state=None, created_at=None, closed_at=None):  # noqa: E501
        """QSchedulerSessionInfoExt - a model defined in Swagger"""  # noqa: E501
        self._session_id = None
        self._cluster_id = None
        self._project_id = None
        self._state = None
        self._created_at = None
        self._closed_at = None
        self.discriminator = None
        if session_id is not None:
            self.session_id = session_id
        if cluster_id is not None:
            self.cluster_id = cluster_id
        if project_id is not None:
            self.project_id = project_id
        if state is not None:
            self.state = state
        if created_at is not None:
            self.created_at = created_at
        if closed_at is not None:
            self.closed_at = closed_at

    @property
    def session_id(self):
        """Gets the session_id of this QSchedulerSessionInfoExt.  # noqa: E501


        :return: The session_id of this QSchedulerSessionInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this QSchedulerSessionInfoExt.


        :param session_id: The session_id of this QSchedulerSessionInfoExt.  # noqa: E501
        :type: int
        """

        self._session_id = session_id

    @property
    def cluster_id(self):
        """Gets the cluster_id of this QSchedulerSessionInfoExt.  # noqa: E501


        :return: The cluster_id of this QSchedulerSessionInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """Sets the cluster_id of this QSchedulerSessionInfoExt.


        :param cluster_id: The cluster_id of this QSchedulerSessionInfoExt.  # noqa: E501
        :type: int
        """

        self._cluster_id = cluster_id

    @property
    def project_id(self):
        """Gets the project_id of this QSchedulerSessionInfoExt.  # noqa: E501


        :return: The project_id of this QSchedulerSessionInfoExt.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this QSchedulerSessionInfoExt.


        :param project_id: The project_id of this QSchedulerSessionInfoExt.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def state(self):
        """Gets the state of this QSchedulerSessionInfoExt.  # noqa: E501


        :return: The state of this QSchedulerSessionInfoExt.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this QSchedulerSessionInfoExt.


        :param state: The state of this QSchedulerSessionInfoExt.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def created_at(self):
        """Gets the created_at of this QSchedulerSessionInfoExt.  # noqa: E501


        :return: The created_at of this QSchedulerSessionInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this QSchedulerSessionInfoExt.


        :param created_at: The created_at of this QSchedulerSessionInfoExt.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def closed_at(self):
        """Gets the closed_at of this QSchedulerSessionInfoExt.  # noqa: E501


        :return: The closed_at of this QSchedulerSessionInfoExt.  # noqa: E501
        :rtype: datetime
        """
        return self._closed_at

    @closed_at.setter
    def closed_at(self, closed_at):
        """Sets the closed_at of this QSchedulerSessionInfoExt.


        :param closed_at: The closed_at of this QSchedulerSessionInfoExt.  # noqa: E501
        :type: datetime
        """

        self._closed_at = closed_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QSchedulerSessionInfoExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QSchedulerSessionInfoExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
