# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RemoveCredentialModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_id': 'int',
        'session_code': 'str',
        'adaptor_user_id': 'int',
        'username': 'str'
    }

    attribute_map = {
        'project_id': 'ProjectId',
        'session_code': 'SessionCode',
        'adaptor_user_id': 'AdaptorUserId',
        'username': 'Username'
    }

    def __init__(self, project_id=None, session_code=None, adaptor_user_id=None, username=None):  # noqa: E501
        """RemoveCredentialModel - a model defined in Swagger"""  # noqa: E501
        self._project_id = None
        self._session_code = None
        self._adaptor_user_id = None
        self._username = None
        self.discriminator = None
        if project_id is not None:
            self.project_id = project_id
        if session_code is not None:
            self.session_code = session_code
        if adaptor_user_id is not None:
            self.adaptor_user_id = adaptor_user_id
        if username is not None:
            self.username = username

    @property
    def project_id(self):
        """Gets the project_id of this RemoveCredentialModel.  # noqa: E501

        Project id  # noqa: E501

        :return: The project_id of this RemoveCredentialModel.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this RemoveCredentialModel.

        Project id  # noqa: E501

        :param project_id: The project_id of this RemoveCredentialModel.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def session_code(self):
        """Gets the session_code of this RemoveCredentialModel.  # noqa: E501

        Session code  # noqa: E501

        :return: The session_code of this RemoveCredentialModel.  # noqa: E501
        :rtype: str
        """
        return self._session_code

    @session_code.setter
    def session_code(self, session_code):
        """Sets the session_code of this RemoveCredentialModel.

        Session code  # noqa: E501

        :param session_code: The session_code of this RemoveCredentialModel.  # noqa: E501
        :type: str
        """

        self._session_code = session_code

    @property
    def adaptor_user_id(self):
        """Gets the adaptor_user_id of this RemoveCredentialModel.  # noqa: E501

        Adaptor user id  # noqa: E501

        :return: The adaptor_user_id of this RemoveCredentialModel.  # noqa: E501
        :rtype: int
        """
        return self._adaptor_user_id

    @adaptor_user_id.setter
    def adaptor_user_id(self, adaptor_user_id):
        """Sets the adaptor_user_id of this RemoveCredentialModel.

        Adaptor user id  # noqa: E501

        :param adaptor_user_id: The adaptor_user_id of this RemoveCredentialModel.  # noqa: E501
        :type: int
        """

        self._adaptor_user_id = adaptor_user_id

    @property
    def username(self):
        """Gets the username of this RemoveCredentialModel.  # noqa: E501

        Username  # noqa: E501

        :return: The username of this RemoveCredentialModel.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this RemoveCredentialModel.

        Username  # noqa: E501

        :param username: The username of this RemoveCredentialModel.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RemoveCredentialModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemoveCredentialModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
