# coding: utf-8

"""
    py4heappe API

    Merged API documentation for py4heappe client  # noqa: E501

    OpenAPI spec version: v6.2.0
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RestoreDatabaseModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_code': 'str',
        'backup_file_name': 'str',
        'include_logs': 'bool'
    }

    attribute_map = {
        'session_code': 'SessionCode',
        'backup_file_name': 'BackupFileName',
        'include_logs': 'IncludeLogs'
    }

    def __init__(self, session_code=None, backup_file_name=None, include_logs=None):  # noqa: E501
        """RestoreDatabaseModel - a model defined in Swagger"""  # noqa: E501
        self._session_code = None
        self._backup_file_name = None
        self._include_logs = None
        self.discriminator = None
        if session_code is not None:
            self.session_code = session_code
        if backup_file_name is not None:
            self.backup_file_name = backup_file_name
        if include_logs is not None:
            self.include_logs = include_logs

    @property
    def session_code(self):
        """Gets the session_code of this RestoreDatabaseModel.  # noqa: E501

        Session code  # noqa: E501

        :return: The session_code of this RestoreDatabaseModel.  # noqa: E501
        :rtype: str
        """
        return self._session_code

    @session_code.setter
    def session_code(self, session_code):
        """Sets the session_code of this RestoreDatabaseModel.

        Session code  # noqa: E501

        :param session_code: The session_code of this RestoreDatabaseModel.  # noqa: E501
        :type: str
        """

        self._session_code = session_code

    @property
    def backup_file_name(self):
        """Gets the backup_file_name of this RestoreDatabaseModel.  # noqa: E501

        Backup file name  # noqa: E501

        :return: The backup_file_name of this RestoreDatabaseModel.  # noqa: E501
        :rtype: str
        """
        return self._backup_file_name

    @backup_file_name.setter
    def backup_file_name(self, backup_file_name):
        """Sets the backup_file_name of this RestoreDatabaseModel.

        Backup file name  # noqa: E501

        :param backup_file_name: The backup_file_name of this RestoreDatabaseModel.  # noqa: E501
        :type: str
        """

        self._backup_file_name = backup_file_name

    @property
    def include_logs(self):
        """Gets the include_logs of this RestoreDatabaseModel.  # noqa: E501

        Include transaction logs backup restore  # noqa: E501

        :return: The include_logs of this RestoreDatabaseModel.  # noqa: E501
        :rtype: bool
        """
        return self._include_logs

    @include_logs.setter
    def include_logs(self, include_logs):
        """Sets the include_logs of this RestoreDatabaseModel.

        Include transaction logs backup restore  # noqa: E501

        :param include_logs: The include_logs of this RestoreDatabaseModel.  # noqa: E501
        :type: bool
        """

        self._include_logs = include_logs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RestoreDatabaseModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RestoreDatabaseModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
