# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StatisticsExt_(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total_checks': 'int',
        'vault_credential': 'VaultCredentialCountsExt_',
        'cluster_connection': 'ClusterConnectionCountsExt_',
        'dry_run_job': 'ClusterConnectionCountsExt_'
    }

    attribute_map = {
        'total_checks': 'TotalChecks',
        'vault_credential': 'VaultCredential',
        'cluster_connection': 'ClusterConnection',
        'dry_run_job': 'DryRunJob'
    }

    def __init__(self, total_checks=None, vault_credential=None, cluster_connection=None, dry_run_job=None):  # noqa: E501
        """StatisticsExt_ - a model defined in Swagger"""  # noqa: E501
        self._total_checks = None
        self._vault_credential = None
        self._cluster_connection = None
        self._dry_run_job = None
        self.discriminator = None
        if total_checks is not None:
            self.total_checks = total_checks
        if vault_credential is not None:
            self.vault_credential = vault_credential
        if cluster_connection is not None:
            self.cluster_connection = cluster_connection
        if dry_run_job is not None:
            self.dry_run_job = dry_run_job

    @property
    def total_checks(self):
        """Gets the total_checks of this StatisticsExt_.  # noqa: E501

        TotalChecks  # noqa: E501

        :return: The total_checks of this StatisticsExt_.  # noqa: E501
        :rtype: int
        """
        return self._total_checks

    @total_checks.setter
    def total_checks(self, total_checks):
        """Sets the total_checks of this StatisticsExt_.

        TotalChecks  # noqa: E501

        :param total_checks: The total_checks of this StatisticsExt_.  # noqa: E501
        :type: int
        """

        self._total_checks = total_checks

    @property
    def vault_credential(self):
        """Gets the vault_credential of this StatisticsExt_.  # noqa: E501


        :return: The vault_credential of this StatisticsExt_.  # noqa: E501
        :rtype: VaultCredentialCountsExt_
        """
        return self._vault_credential

    @vault_credential.setter
    def vault_credential(self, vault_credential):
        """Sets the vault_credential of this StatisticsExt_.


        :param vault_credential: The vault_credential of this StatisticsExt_.  # noqa: E501
        :type: VaultCredentialCountsExt_
        """

        self._vault_credential = vault_credential

    @property
    def cluster_connection(self):
        """Gets the cluster_connection of this StatisticsExt_.  # noqa: E501


        :return: The cluster_connection of this StatisticsExt_.  # noqa: E501
        :rtype: ClusterConnectionCountsExt_
        """
        return self._cluster_connection

    @cluster_connection.setter
    def cluster_connection(self, cluster_connection):
        """Sets the cluster_connection of this StatisticsExt_.


        :param cluster_connection: The cluster_connection of this StatisticsExt_.  # noqa: E501
        :type: ClusterConnectionCountsExt_
        """

        self._cluster_connection = cluster_connection

    @property
    def dry_run_job(self):
        """Gets the dry_run_job of this StatisticsExt_.  # noqa: E501


        :return: The dry_run_job of this StatisticsExt_.  # noqa: E501
        :rtype: ClusterConnectionCountsExt_
        """
        return self._dry_run_job

    @dry_run_job.setter
    def dry_run_job(self, dry_run_job):
        """Sets the dry_run_job of this StatisticsExt_.


        :param dry_run_job: The dry_run_job of this StatisticsExt_.  # noqa: E501
        :type: ClusterConnectionCountsExt_
        """

        self._dry_run_job = dry_run_job

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatisticsExt_, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatisticsExt_):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
