# coding: utf-8

"""
    py4heappe API

    Merged API documentation for py4heappe client  # noqa: E501

    OpenAPI spec version: v6.1.1
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StatusCheckLogsExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'by_cluster_authentication_credential': 'list[ByClusterAuthenticationCredentialExt]'
    }

    attribute_map = {
        'by_cluster_authentication_credential': 'ByClusterAuthenticationCredential'
    }

    def __init__(self, by_cluster_authentication_credential=None):  # noqa: E501
        """StatusCheckLogsExt - a model defined in Swagger"""  # noqa: E501
        self._by_cluster_authentication_credential = None
        self.discriminator = None
        if by_cluster_authentication_credential is not None:
            self.by_cluster_authentication_credential = by_cluster_authentication_credential

    @property
    def by_cluster_authentication_credential(self):
        """Gets the by_cluster_authentication_credential of this StatusCheckLogsExt.  # noqa: E501

        ByClusterAuthenticationCredential  # noqa: E501

        :return: The by_cluster_authentication_credential of this StatusCheckLogsExt.  # noqa: E501
        :rtype: list[ByClusterAuthenticationCredentialExt]
        """
        return self._by_cluster_authentication_credential

    @by_cluster_authentication_credential.setter
    def by_cluster_authentication_credential(self, by_cluster_authentication_credential):
        """Sets the by_cluster_authentication_credential of this StatusCheckLogsExt.

        ByClusterAuthenticationCredential  # noqa: E501

        :param by_cluster_authentication_credential: The by_cluster_authentication_credential of this StatusCheckLogsExt.  # noqa: E501
        :type: list[ByClusterAuthenticationCredentialExt]
        """

        self._by_cluster_authentication_credential = by_cluster_authentication_credential

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatusCheckLogsExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatusCheckLogsExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
