# coding: utf-8

"""
    py4heappe API

    Merged API documentation for py4heappe client  # noqa: E501

    OpenAPI spec version: v6.1.1
    Contact: support.heappe@it4i.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StatusExt(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_id': 'int',
        'time_from': 'datetime',
        'time_to': 'datetime',
        'statistics': 'StatisticsExt_',
        'details': 'list[DetailExt_]'
    }

    attribute_map = {
        'project_id': 'ProjectId',
        'time_from': 'TimeFrom',
        'time_to': 'TimeTo',
        'statistics': 'Statistics',
        'details': 'Details'
    }

    def __init__(self, project_id=None, time_from=None, time_to=None, statistics=None, details=None):  # noqa: E501
        """StatusExt - a model defined in Swagger"""  # noqa: E501
        self._project_id = None
        self._time_from = None
        self._time_to = None
        self._statistics = None
        self._details = None
        self.discriminator = None
        if project_id is not None:
            self.project_id = project_id
        if time_from is not None:
            self.time_from = time_from
        if time_to is not None:
            self.time_to = time_to
        if statistics is not None:
            self.statistics = statistics
        if details is not None:
            self.details = details

    @property
    def project_id(self):
        """Gets the project_id of this StatusExt.  # noqa: E501

        ProjectId  # noqa: E501

        :return: The project_id of this StatusExt.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this StatusExt.

        ProjectId  # noqa: E501

        :param project_id: The project_id of this StatusExt.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def time_from(self):
        """Gets the time_from of this StatusExt.  # noqa: E501

        TimeFrom  # noqa: E501

        :return: The time_from of this StatusExt.  # noqa: E501
        :rtype: datetime
        """
        return self._time_from

    @time_from.setter
    def time_from(self, time_from):
        """Sets the time_from of this StatusExt.

        TimeFrom  # noqa: E501

        :param time_from: The time_from of this StatusExt.  # noqa: E501
        :type: datetime
        """

        self._time_from = time_from

    @property
    def time_to(self):
        """Gets the time_to of this StatusExt.  # noqa: E501

        TimeTo  # noqa: E501

        :return: The time_to of this StatusExt.  # noqa: E501
        :rtype: datetime
        """
        return self._time_to

    @time_to.setter
    def time_to(self, time_to):
        """Sets the time_to of this StatusExt.

        TimeTo  # noqa: E501

        :param time_to: The time_to of this StatusExt.  # noqa: E501
        :type: datetime
        """

        self._time_to = time_to

    @property
    def statistics(self):
        """Gets the statistics of this StatusExt.  # noqa: E501


        :return: The statistics of this StatusExt.  # noqa: E501
        :rtype: StatisticsExt_
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics):
        """Sets the statistics of this StatusExt.


        :param statistics: The statistics of this StatusExt.  # noqa: E501
        :type: StatisticsExt_
        """

        self._statistics = statistics

    @property
    def details(self):
        """Gets the details of this StatusExt.  # noqa: E501

        Details  # noqa: E501

        :return: The details of this StatusExt.  # noqa: E501
        :rtype: list[DetailExt_]
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this StatusExt.

        Details  # noqa: E501

        :param details: The details of this StatusExt.  # noqa: E501
        :type: list[DetailExt_]
        """

        self._details = details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StatusExt, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatusExt):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
