# coding: utf-8

"""
    py4heappe API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TaskCallbackModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'task_id': 'str',
        'session_id': 'str',
        'token': 'str',
        'raw_response': 'str',
        'state': 'str',
        'event': 'str',
        'task': 'object',
        'session': 'object'
    }

    attribute_map = {
        'task_id': 'task_id',
        'session_id': 'session_id',
        'token': 'token',
        'raw_response': 'raw_response',
        'state': 'state',
        'event': 'event',
        'task': 'task',
        'session': 'session'
    }

    def __init__(self, task_id=None, session_id=None, token=None, raw_response=None, state=None, event=None, task=None, session=None):  # noqa: E501
        """TaskCallbackModel - a model defined in Swagger"""  # noqa: E501
        self._task_id = None
        self._session_id = None
        self._token = None
        self._raw_response = None
        self._state = None
        self._event = None
        self._task = None
        self._session = None
        self.discriminator = None
        if task_id is not None:
            self.task_id = task_id
        if session_id is not None:
            self.session_id = session_id
        self.token = token
        if raw_response is not None:
            self.raw_response = raw_response
        if state is not None:
            self.state = state
        if event is not None:
            self.event = event
        if task is not None:
            self.task = task
        if session is not None:
            self.session = session

    @property
    def task_id(self):
        """Gets the task_id of this TaskCallbackModel.  # noqa: E501


        :return: The task_id of this TaskCallbackModel.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this TaskCallbackModel.


        :param task_id: The task_id of this TaskCallbackModel.  # noqa: E501
        :type: str
        """

        self._task_id = task_id

    @property
    def session_id(self):
        """Gets the session_id of this TaskCallbackModel.  # noqa: E501


        :return: The session_id of this TaskCallbackModel.  # noqa: E501
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this TaskCallbackModel.


        :param session_id: The session_id of this TaskCallbackModel.  # noqa: E501
        :type: str
        """

        self._session_id = session_id

    @property
    def token(self):
        """Gets the token of this TaskCallbackModel.  # noqa: E501


        :return: The token of this TaskCallbackModel.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this TaskCallbackModel.


        :param token: The token of this TaskCallbackModel.  # noqa: E501
        :type: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token

    @property
    def raw_response(self):
        """Gets the raw_response of this TaskCallbackModel.  # noqa: E501


        :return: The raw_response of this TaskCallbackModel.  # noqa: E501
        :rtype: str
        """
        return self._raw_response

    @raw_response.setter
    def raw_response(self, raw_response):
        """Sets the raw_response of this TaskCallbackModel.


        :param raw_response: The raw_response of this TaskCallbackModel.  # noqa: E501
        :type: str
        """

        self._raw_response = raw_response

    @property
    def state(self):
        """Gets the state of this TaskCallbackModel.  # noqa: E501


        :return: The state of this TaskCallbackModel.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this TaskCallbackModel.


        :param state: The state of this TaskCallbackModel.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def event(self):
        """Gets the event of this TaskCallbackModel.  # noqa: E501


        :return: The event of this TaskCallbackModel.  # noqa: E501
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this TaskCallbackModel.


        :param event: The event of this TaskCallbackModel.  # noqa: E501
        :type: str
        """

        self._event = event

    @property
    def task(self):
        """Gets the task of this TaskCallbackModel.  # noqa: E501


        :return: The task of this TaskCallbackModel.  # noqa: E501
        :rtype: object
        """
        return self._task

    @task.setter
    def task(self, task):
        """Sets the task of this TaskCallbackModel.


        :param task: The task of this TaskCallbackModel.  # noqa: E501
        :type: object
        """

        self._task = task

    @property
    def session(self):
        """Gets the session of this TaskCallbackModel.  # noqa: E501


        :return: The session of this TaskCallbackModel.  # noqa: E501
        :rtype: object
        """
        return self._session

    @session.setter
    def session(self, session):
        """Sets the session of this TaskCallbackModel.


        :param session: The session of this TaskCallbackModel.  # noqa: E501
        :type: object
        """

        self._session = session

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskCallbackModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskCallbackModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
